/**
 * Checked-in Web copy of the public v1 action/RBAC contract.
 *
 * The UI still renders the role-filtered capabilities returned by the control
 * plane; this table is not an optimistic fallback. It exists so Web builds fail
 * when the published action matrix changes without a deliberate client update.
 */
export const WEB_V1_ACTIONS = [
  ["catalog.list", "Catalog", "viewer", false],
  ["catalog.search", "Catalog", "viewer", false],
  ["catalog.register", "Catalog", "admin", false],
  ["catalog.remove", "Catalog", "admin", false],
  ["release.import", "Release", "operator", false],
  ["release.validate", "Release", "operator", false],
  ["release.install", "Release", "operator", true],
  ["release.upgrade", "Release", "operator", true],
  ["release.rollback", "Release", "operator", true],
  ["release.delete", "Release", "admin", false],
  ["node.register", "Node", "admin", false],
  ["node.revoke", "Node", "admin", false],
  ["node.list", "Node", "viewer", false],
  ["node.health", "Node", "viewer", false],
  ["node.drain", "Node", "admin", true],
  ["node.remove", "Node", "admin", true],
  ["deployment.list", "Deployment", "viewer", false],
  ["deployment.get", "Deployment", "viewer", false],
  ["deployment.start", "Deployment", "operator", true],
  ["deployment.stop", "Deployment", "operator", true],
  ["deployment.restart", "Deployment", "operator", true],
  ["deployment.uninstall", "Deployment", "admin", true],
  ["deployment.health", "Deployment", "viewer", false],
  ["resource.purge", "ResourceClaim", "admin", true],
  ["topology.draft", "Topology", "operator", false],
  ["topology.revision", "Topology", "operator", false],
  ["topology.endpoint.edit", "Topology", "operator", false],
  ["topology.link.edit", "Topology", "operator", false],
  ["topology.validate", "Topology", "operator", false],
  ["topology.diff", "Topology", "operator", false],
  ["topology.apply", "Topology", "operator", true],
  ["topology.rollback", "Topology", "operator", true],
  ["topology.status", "Topology", "viewer", false],
  ["topology.export", "Topology", "viewer", false],
  ["operation.plan", "Operation", "operator", false],
  ["operation.confirm", "Operation", "operator", false],
  ["operation.apply", "Operation", "operator", true],
  ["operation.cancel", "Operation", "operator", true],
  ["operation.retry", "Operation", "operator", true],
  ["operation.rollback", "Operation", "operator", true],
  ["operation.logs", "Operation", "viewer", false],
  ["operation.events", "Operation", "viewer", false],
  ["diagnostic.create", "Diagnostic", "operator", false],
  ["diagnostic.list", "Diagnostic", "viewer", false],
  ["diagnostic.get", "Diagnostic", "viewer", false],
  ["diagnostic.export", "Diagnostic", "viewer", false],
] as const;

export const WEB_V1_ROLE_PERMISSIONS = {
  viewer: "orchestrator.read",
  operator: "orchestrator.operate",
  admin: "orchestrator.admin",
} as const;

/** Concrete Web SDK method for every capability returned by `/capabilities`. */
export const WEB_V1_ACTION_METHODS = {
  "catalog.list": "catalogs",
  "catalog.search": "storeIndex",
  "catalog.register": "registerCatalog",
  "catalog.remove": "removeCatalog",
  "release.import": "storeImport",
  "release.validate": "storeValidate",
  "release.install": "storeInstall",
  "release.upgrade": "storeUpgrade",
  "release.rollback": "storeRollback",
  "release.delete": "deleteRelease",
  "node.register": "createNodeEnrollment",
  "node.revoke": "revokeNodeCertificates",
  "node.list": "nodes",
  "node.health": "nodeHealth",
  "node.drain": "nodeDrain",
  "node.remove": "nodeRemove",
  "deployment.list": "deployments",
  "deployment.get": "deployment",
  "deployment.start": "deploymentAction",
  "deployment.stop": "deploymentAction",
  "deployment.restart": "deploymentAction",
  "deployment.uninstall": "deploymentAction",
  "deployment.health": "deploymentHealth",
  "resource.purge": "resourcePurge",
  "topology.draft": "topologyCreate",
  "topology.revision": "topologyCreateRevision",
  "topology.endpoint.edit": "topologyPutEndpoint",
  "topology.link.edit": "topologyPutLink",
  "topology.validate": "topologyValidate",
  "topology.diff": "topologyDiff",
  "topology.apply": "topologyApply",
  "topology.rollback": "topologyRollback",
  "topology.status": "topologyStatus",
  "topology.export": "topology",
  "operation.plan": "operationPlan",
  "operation.confirm": "operationConfirm",
  "operation.apply": "operationApply",
  "operation.cancel": "operationCancel",
  "operation.retry": "operationRetry",
  "operation.rollback": "operationRollback",
  "operation.logs": "operationLogs",
  "operation.events": "operationEvents",
  "diagnostic.create": "createDiagnostic",
  "diagnostic.list": "diagnostics",
  "diagnostic.get": "diagnostic",
  "diagnostic.export": "exportDiagnostic",
} as const;
