// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BucketsResp struct {
	Buckets []string `json:"buckets"`
}

type DeleteObjectResp struct {
	Deleted bool `json:"deleted"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Service string `json:"service"`
}

type ObjectMetadata struct {
	Bucket      string `json:"bucket"`
	Key         string `json:"key"`
	SizeBytes   int64  `json:"size_bytes"`
	SHA256      string `json:"sha256"`
	ContentType string `json:"content_type"`
	UpdatedAt   string `json:"updated_at"`
}

type ObjectReq struct {
	Bucket string `path:"bucket"`
	Key    string `path:"key"`
}
