// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BucketsResp struct {
	Buckets []string `json:"buckets"`
}

type BucketReq struct {
	Bucket string `path:"bucket"`
}

type BucketResp struct {
	Bucket  string `json:"bucket"`
	Created bool   `json:"created"`
}

type DeleteObjectResp struct {
	Deleted bool `json:"deleted"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Backend string `json:"backend"`
}

type ListObjectsReq struct {
	Bucket string `path:"bucket"`
	Prefix string `form:"prefix,optional"`
	Cursor string `form:"cursor,optional"`
	Limit  int    `form:"limit,optional"`
}

type ListObjectsResp struct {
	Objects    []ObjectMetadata `json:"objects"`
	NextCursor string           `json:"next_cursor,omitempty"`
}

type ObjectMetadata struct {
	Bucket      string `json:"bucket"`
	Key         string `json:"key"`
	SizeBytes   int64  `json:"size_bytes"`
	SHA256      string `json:"sha256"`
	ContentType string `json:"content_type"`
	UpdatedAt   string `json:"updated_at"`
}

type ObjectReq struct {
	Bucket string `path:"bucket"`
	Key    string `path:"key"`
}
