service:
  name: auth-service
  port: 8081

database:
  url: postgres://postgres:password@postgres:5432/ojos?sslmode=disable

jaeger:
  endpoint: ojos-jaeger:4317

nats:
  url: nats://ojos-nats:4222

jwt:
  secret: ojos-dev-secret-change-me
  expire_hours: 24