[package]
name = "orchestrator-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
regex.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
