// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResp struct {
	Status  string `json:"status"`
	Service string `json:"service"`
}

type PreferencesResp struct {
	Preferences map[string]string `json:"preferences"`
}

type ProfilePatchReq struct {
	UserId       string            `path:"user_id"`
	DisplayName  string            `json:"display_name,optional"`
	Bio          string            `json:"bio,optional"`
	AvatarObject string            `json:"avatar_object,optional"`
	Preferences  map[string]string `json:"preferences,optional"`
}

type ProfileReq struct {
	UserId string `path:"user_id"`
}

type ProfileResp struct {
	UserId       string            `json:"user_id"`
	DisplayName  string            `json:"display_name"`
	Bio          string            `json:"bio"`
	AvatarObject string            `json:"avatar_object"`
	Preferences  map[string]string `json:"preferences"`
	Stats        UserStats         `json:"stats"`
	CreatedAt    string            `json:"created_at"`
	UpdatedAt    string            `json:"updated_at"`
}

type UserStats struct {
	SolvedProblems int `json:"solved_problems"`
	Submissions    int `json:"submissions"`
	Accepted       int `json:"accepted"`
}
