// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddTestCaseReq struct {
	ProblemId int64  `json:"problem_id"`
	Input     string `json:"input"`
	Output    string `json:"output"`
	Score     int    `json:"score,optional"`
}

type AddTestCaseResp struct {
	TestCaseId int64 `json:"test_case_id"`
}

type CreateProblemReq struct {
	Title         string `json:"title"`
	TimeLimitMs   int    `json:"time_limit_ms,optional"`
	MemoryLimitMb int    `json:"memory_limit_mb,optional"`
}

type CreateProblemResp struct {
	ProblemId int64 `json:"problem_id"`
}

type CreateSubmissionReq struct {
	ProblemId int64  `json:"problem_id"`
	Language  string `json:"language,optional"`
	Code      string `json:"code"`
}

type CreateSubmissionResp struct {
	SubmissionId int64  `json:"submission_id"`
	Status       string `json:"status"`
}

type GetSubmissionCasesReq struct {
	Id int64 `path:"id"`
}

type GetSubmissionCasesResp struct {
	Cases []SubmissionCaseItem `json:"cases"`
}

type GetSubmissionReq struct {
	Id int64 `path:"id"`
}

type GetSubmissionResp struct {
	Id        int64  `json:"id"`
	ProblemId int64  `json:"problem_id"`
	UserId    int64  `json:"user_id"`
	Language  string `json:"language"`
	Status    string `json:"status"`
	Score     int    `json:"score"`
	TimeMs    int    `json:"time_ms"`
	MemoryKb  int    `json:"memory_kb"`
	Message   string `json:"message,optional"`
}

type SubmissionCaseItem struct {
	Id           int64  `json:"id"`
	SubmissionId int64  `json:"submission_id"`
	TestCaseId   int64  `json:"test_case_id"`
	Status       string `json:"status"`
	TimeMs       int    `json:"time_ms"`
	MemoryKb     int    `json:"memory_kb"`
	Message      string `json:"message,optional"`
}
