// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CancelSubmissionReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason,optional"`
}

type CancelSubmissionResp struct {
	SubmissionId int64  `json:"submission_id"`
	Status       string `json:"status"`
}

type CreateSubmissionReq struct {
	ProblemId int64  `json:"problem_id"`
	Language  string `json:"language,optional"`
	Code      string `json:"code"`
}

type CreateSubmissionResp struct {
	SubmissionId int64  `json:"submission_id"`
	Status       string `json:"status"`
}

type GetSubmissionCasesReq struct {
	Id int64 `path:"id"`
}

type GetSubmissionCasesResp struct {
	Cases []SubmissionCaseItem `json:"cases"`
}

type GetSubmissionReq struct {
	Id int64 `path:"id"`
}

type GetSubmissionResp struct {
	Id           int64  `json:"id"`
	ProblemId    int64  `json:"problem_id"`
	UserId       int64  `json:"user_id"`
	Language     string `json:"language"`
	Status       string `json:"status"`
	Score        int    `json:"score"`
	TimeMs       int    `json:"time_ms"`
	MemoryKb     int    `json:"memory_kb"`
	Message      string `json:"message,optional"`
	CodeSha256   string `json:"code_sha256"`
	JudgedAt     string `json:"judged_at,optional"`
	CancelledAt  string `json:"cancelled_at,optional"`
	CancelReason string `json:"cancel_reason,optional"`
}

type RejudgeProblemReq struct {
	Id int64 `path:"id"`
}

type RejudgeProblemResp struct {
	ProblemId int64 `json:"problem_id"`
	Enqueued  int   `json:"enqueued"`
}

type SubmissionCaseItem struct {
	CaseNo   int    `json:"case_no"`
	Status   string `json:"status"`
	Score    int    `json:"score"`
	TimeMs   int    `json:"time_ms"`
	MemoryKb int    `json:"memory_kb"`
	Message  string `json:"message,optional"`
}
