// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-judge-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/problems",
					Handler: createProblemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submissions",
					Handler: createSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id",
					Handler: getSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id/cases",
					Handler: getSubmissionCasesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/test-cases",
					Handler: addTestCaseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/judge"),
	)
}
