// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-judge-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.InternalAuthMiddleware,
				serverCtx.WorkerAuthMiddleware,
			},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/worker/register",
					Handler: workerRegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/worker/heartbeat",
					Handler: workerHeartbeatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/worker/tasks/claim",
					Handler: workerClaimTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/worker/tasks/:task_id/heartbeat",
					Handler: workerTaskHeartbeatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/worker/tasks/:task_id/result",
					Handler: workerSubmitResultHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/worker/tasks/:task_id/fail",
					Handler: workerFailTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/worker/artifacts/submissions/:id/source",
					Handler: workerArtifactSubmissionSourceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/worker/artifacts/problems/:id/package",
					Handler: workerArtifactProblemPackageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/judge"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.InternalAuthMiddleware,
				serverCtx.UserContextMiddleware,
			},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/languages",
					Handler: listLanguagesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/queue",
					Handler: adminQueueHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/workers",
					Handler: adminWorkersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/tasks",
					Handler: adminTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/workers/:id/drain",
					Handler: adminDrainWorkerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/submissions/:id/requeue",
					Handler: adminRequeueSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submissions",
					Handler: createSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions",
					Handler: listSubmissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id/cases",
					Handler: getSubmissionCasesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id/debug-logs",
					Handler: getSubmissionDebugLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submissions/:id/cancel",
					Handler: cancelSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id",
					Handler: getSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/problems/:id/rejudge",
					Handler: rejudgeProblemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/judge"),
	)
}
