// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"
	"time"

	"ojos-judge-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

const workerClaimRouteTimeout = 35 * time.Second

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: readyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/queue",
					Handler: adminQueueHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/queue/status",
					Handler: adminQueueStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/submissions/:id/requeue",
					Handler: adminRequeueSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/tasks",
					Handler: adminTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/workers",
					Handler: adminWorkersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/workers/:id/drain",
					Handler: adminDrainWorkerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/languages",
					Handler: listLanguagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/problems/:id/rejudge",
					Handler: rejudgeProblemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submissions",
					Handler: createSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions",
					Handler: listSubmissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id",
					Handler: getSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/submissions/:id/cancel",
					Handler: cancelSubmissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id/cases",
					Handler: getSubmissionCasesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/submissions/:id/debug-logs",
					Handler: getSubmissionDebugLogsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/judge"),
	)

	workerRoutes := []rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/worker/artifacts/problems/:id/package",
			Handler: workerArtifactProblemPackageHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/worker/artifacts/submissions/:id/source",
			Handler: workerArtifactSubmissionSourceHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/worker/heartbeat",
			Handler: workerHeartbeatHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/worker/register",
			Handler: workerRegisterHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/worker/tasks/:task_id/fail",
			Handler: workerFailTaskHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/worker/tasks/:task_id/heartbeat",
			Handler: workerTaskHeartbeatHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/worker/tasks/:task_id/result",
			Handler: workerSubmitResultHandler(serverCtx),
		},
	}
	workerClaimRoutes := []rest.Route{{
		Method:  http.MethodPost,
		Path:    "/worker/tasks/claim",
		Handler: workerClaimTasksHandler(serverCtx),
	}}
	if !serverCtx.Managed {
		registerWorkerRoutes(server, serverCtx, "/judge", workerRoutes, workerClaimRoutes)
	}
	// Service Contract v2 paths are provider-native and therefore retain the
	// public /api prefix. The legacy /judge prefix remains for the development
	// Compose gateway, which historically strips /api before proxying.
	registerWorkerRoutes(server, serverCtx, "/api/judge", workerRoutes, workerClaimRoutes)
}

func registerWorkerRoutes(
	server *rest.Server,
	serverCtx *svc.ServiceContext,
	prefix string,
	workerRoutes []rest.Route,
	workerClaimRoutes []rest.Route,
) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WorkerAuthMiddleware},
			workerRoutes...,
		),
		rest.WithPrefix(prefix),
	)
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WorkerAuthMiddleware},
			workerClaimRoutes...,
		),
		rest.WithPrefix(prefix),
		rest.WithTimeout(workerClaimRouteTimeout),
	)
}
