// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-problem-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/artifact-gc/intents",
					Handler: listArtifactGCIntentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/artifact-gc/intents:reconcile",
					Handler: reconcileArtifactGCIntentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/artifact-gc/intents:retry",
					Handler: retryArtifactGCIntentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/problems",
					Handler: createProblemHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/problems",
					Handler: listProblemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/problems/:id",
					Handler: getProblemHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/problems/:id",
					Handler: updateProblemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/problems/:id",
					Handler: deleteProblemHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/problems/:id/package",
					Handler: getProblemPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/problems/:id/package/cases",
					Handler: listPackageCasesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/problems/:id/package/validate",
					Handler: validateProblemPackageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/problems/:id/test-cases",
					Handler: addTestCaseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/problems/:id/test-cases",
					Handler: listTestCasesHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/problems/:id/test-cases/:case_no",
					Handler: updateTestCaseHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/problems/:id/test-cases/:case_no",
					Handler: deleteTestCaseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/problem"),
	)
}
