// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthData struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}

type HealthResp struct {
	Code int        `json:"code"`
	Msg  string     `json:"msg"`
	Data HealthData `json:"data"`
}

type LoginData struct {
	Token    string   `json:"token"`
	UserId   int64    `json:"user_id"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code int       `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginData `json:"data,optional"`
}

type ProfileData struct {
	UserId   int64    `json:"user_id"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type ProfileResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data ProfileData `json:"data,optional"`
}

type RegisterData struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email,optional"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data RegisterData `json:"data,optional"`
}
