// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-auth-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: registerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/audit-logs",
					Handler: listAuditLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/permission-check",
					Handler: permissionCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/permissions",
					Handler: listPermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/problems/roles",
					Handler: addProblemRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/problems/roles",
					Handler: removeProblemRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/roles",
					Handler: listRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/services/:service_code/permissions",
					Handler: registerServicePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/services/:service_code/permissions",
					Handler: deleteServicePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:user_id/effective-permissions",
					Handler: userEffectivePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users",
					Handler: listUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/users/roles",
					Handler: addUserRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/users/roles",
					Handler: removeUserRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: meHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permission-check",
					Handler: userPermissionCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: profileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/auth"),
	)
}
