// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-auth-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	if serverCtx.AdminBootstrap != nil {
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/bootstrap/admin",
					Handler: adminBootstrapHandler(serverCtx),
				},
			},
			rest.WithPrefix("/auth"),
		)
	}

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/api/v1/topologies/:id", Handler: topologyProjectionHandler(serverCtx)},
			{Method: http.MethodPut, Path: "/api/v1/topologies/:id", Handler: topologyProjectionHandler(serverCtx)},
			{Method: http.MethodDelete, Path: "/api/v1/topologies/:id", Handler: topologyProjectionHandler(serverCtx)},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: runtimeHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: runtimeReadyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/.well-known/workload-jwks.json",
				Handler: workloadJWKSHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WorkloadControlPlaneMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/internal/workload-tokens:issue",
					Handler: workloadTokenIssueHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: registerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/audit-logs",
					Handler: listAuditLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/permission-assignments",
					Handler: assignPermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/permission-assignments",
					Handler: listPermissionAssignmentsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/permission-assignments",
					Handler: revokePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/permissions",
					Handler: listPermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/permissions",
					Handler: upsertPermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/permissions",
					Handler: deletePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/problems/roles",
					Handler: addProblemRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/problems/roles",
					Handler: removeProblemRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/resource-edges",
					Handler: addResourceEdgeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/resource-edges",
					Handler: listResourceEdgesHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/resource-edges",
					Handler: removeResourceEdgeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/role-bindings",
					Handler: bindRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/role-bindings",
					Handler: listRoleBindingsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/role-bindings",
					Handler: unbindRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/roles",
					Handler: listRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/roles",
					Handler: upsertRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/roles",
					Handler: deleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/role-permissions",
					Handler: grantRolePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/role-permissions",
					Handler: revokeRolePermissionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/resource-types",
					Handler: upsertResourceTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/resource-types",
					Handler: listResourceTypesHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/resource-types",
					Handler: deleteResourceTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/services/:service_code/identity",
					Handler: getServiceIdentityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/services/:service_code/credentials",
					Handler: addServiceCredentialHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/services/:service_code/credentials/revoke",
					Handler: revokeServiceCredentialHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/services/:service_code/permissions",
					Handler: registerServicePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/services/:service_code/permissions",
					Handler: deleteServicePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:user_id/effective-permissions",
					Handler: userEffectivePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users",
					Handler: listUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/users/roles",
					Handler: addUserRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/users/roles",
					Handler: removeUserRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: meHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/permission-check",
					Handler: userPermissionCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: profileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.DelegatedPermissionMiddleware},
			[]rest.Route{{
				Method: http.MethodPost, Path: "/admin/permission-check",
				Handler: permissionCheckHandler(serverCtx),
			}}...,
		),
		rest.WithPrefix("/auth"),
	)
}
