#!/usr/bin/env python3
"""Hermetic services used by the two-Docker-Engine equivalence gate.

The fixture deliberately implements protocols, not Orchestrator behavior.  The
binding table is generated by the harness from Release v2 manifests and is
passed to the Gateway at runtime.  In particular the Gateway has no hard-coded
knowledge of the third-party echo API.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import http.client
import io
import json
import os
import socket
import ssl
import subprocess
import threading
import time
import urllib.error
import urllib.request
import zipfile
from functools import partial
from http.server import BaseHTTPRequestHandler, SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlsplit


CONTROL_TOKEN = "cross-machine-fixture-control"
DEFAULT_WORKLOAD_TOKEN = "fixture.deployment.jwt.generation-1"
BINDING_HEAD_TIMEOUT_SECONDS = 10
FORGED_IDENTITY_HEADERS = {
    "x-ojos-caller-service",
    "x-ojos-caller-node-id",
    "x-ojos-node-id",
    "x-ojos-consumer-deployment-id",
}


class NoRedirectHandler(urllib.request.HTTPRedirectHandler):
    """Never forward a workload bearer token across a redirect."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def canonical_json(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def sha256_prefixed(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def deterministic_problem_zip() -> bytes:
    files = {
        "problem.yaml": """schema: ojos.problem.v1
id: 1
slug: cross-machine-contract
title: Cross-machine contract
type: traditional
visibility: public
status: published
limits:
  default:
    time_ms: 3000
    memory_mb: 256
  languages: {}
runner:
  config: runner.yaml
checker:
  config: checker.yaml
validator:
  config: validator.yaml
scorer:
  config: scorer.yaml
tests:
  root: tests
  groups: tests/groups.yaml
  cases: tests/cases.yaml
""",
        "runner.yaml": "type: builtin\nname: traditional-runner\nconfig: {}\n",
        "checker.yaml": "type: builtin\nname: default-trim-checker\nconfig: {}\n",
        "validator.yaml": "type: builtin\nname: default-input-validator\nconfig: {}\n",
        "scorer.yaml": "type: builtin\nname: default-sum-scorer\nconfig: {}\n",
        "tests/groups.yaml": "groups:\n  - group_no: 1\n    score: 100\n    rule: sum\n",
        "tests/cases.yaml": (
            "cases:\n"
            "  - case_no: 1\n"
            "    input: 001.in\n"
            "    answer: 001.ans\n"
            "    score: 100\n"
            "    group: 1\n"
            "    sample: true\n"
        ),
        "tests/001.in": "1 1\n",
        "tests/001.ans": "ok\n",
    }
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name in sorted(files):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            info.create_system = 3
            archive.writestr(info, files[name].encode("utf-8"))
    return output.getvalue()


class FixtureState:
    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.objects: dict[str, bytes] = {}
        self.task: dict[str, Any] | None = None
        self.task_state = "absent"
        self.result: dict[str, Any] | None = None
        self.transitions: list[str] = []
        self.claim_prefer = ""
        self.claim_wait_ms = 0
        self.identity_headers_removed = True
        self.workload_requests = 0
        self.third_party_calls = 0

    def create_problem(self) -> dict[str, Any]:
        source = b'#include <iostream>\nint main(){std::cout << "ok\\n";return 0;}\n'
        package = deterministic_problem_zip()
        package_digest = sha256_prefixed(package)
        package_key = "/problems/objects/" + package_digest
        with self.lock:
            self.objects["/submissions/submission-1/main.cpp"] = source
            self.objects[package_key] = package
            self.transitions.extend(
                [
                    "problem.transaction_committed_with_outbox",
                    "problem.snapshot_published",
                    "judge.inbox_recorded",
                    "judge.problem_projection_applied",
                ]
            )
        return {
            "problem_id": 1,
            "aggregate_version": 1,
            "package_revision": 1,
            "package_artifact": {
                "binding": "storage_get",
                "api_id": "storage.object.get",
                "relative_path": package_key,
                "sha256": package_digest,
                "size_bytes": len(package),
            },
        }

    def create_submission(self) -> dict[str, Any]:
        with self.lock:
            if "judge.problem_projection_applied" not in self.transitions:
                raise ValueError("problem projection is not available")
            source_path = "/submissions/submission-1/main.cpp"
            package_path = next(
                (key for key in self.objects if key.startswith("/problems/objects/sha256:")),
                "",
            )
            source = self.objects[source_path]
            package = self.objects[package_path]
            self.task = {
                "task_id": "task-1",
                "submission_id": 1,
                "problem_id": 1,
                "language": "cpp17",
                "attempt": 1,
                "lease_version": 1,
                "lease_expires_at": "2099-01-01T00:00:00Z",
                "source": {
                    "url": "",
                    "binding": "storage_get",
                    "api_id": "storage.object.get",
                    "relative_path": source_path,
                    "sha256": sha256_prefixed(source),
                    "size_bytes": len(source),
                },
                "problem_package": {
                    "url": "",
                    "binding": "storage_get",
                    "api_id": "storage.object.get",
                    "relative_path": package_path,
                    "sha256": sha256_prefixed(package),
                    "size_bytes": len(package),
                },
                "traceparent": "00-11111111111111111111111111111111-2222222222222222-01",
            }
            self.task_state = "queued"
            self.transitions.append("judge.submission_froze_problem_revision")
            self.transitions.append("judge.task_queued")
            return {"submission_id": 1, "task_id": "task-1"}

    def evidence(self) -> dict[str, Any]:
        with self.lock:
            task = json.loads(json.dumps(self.task)) if self.task else None
            return {
                "transitions": list(self.transitions),
                "task_state": self.task_state,
                "result": self.result,
                "task": task,
                "claim_prefer": self.claim_prefer,
                "claim_wait_ms": self.claim_wait_ms,
                "identity_headers_removed": self.identity_headers_removed,
                "workload_requests": self.workload_requests,
                "third_party_calls": self.third_party_calls,
            }


STATE = FixtureState()


def read_json_body(handler: BaseHTTPRequestHandler) -> dict[str, Any]:
    size = int(handler.headers.get("content-length", "0"))
    if size <= 0:
        return {}
    if size > 2 * 1024 * 1024:
        raise ValueError("request body is too large")
    value = json.loads(handler.rfile.read(size))
    if not isinstance(value, dict):
        raise ValueError("request body must be an object")
    return value


def write_json(handler: BaseHTTPRequestHandler, status: int, value: Any) -> None:
    body = canonical_json(value)
    handler.send_response(status)
    handler.send_header("content-type", "application/json")
    handler.send_header("content-length", str(len(body)))
    handler.end_headers()
    if handler.command != "HEAD":
        handler.wfile.write(body)


class QuietHandler(BaseHTTPRequestHandler):
    server_version = "ojos-cross-machine-fixture/1"

    def log_message(self, fmt: str, *args: Any) -> None:
        print(fmt % args, flush=True)


class PlainServiceHandler(QuietHandler):
    def do_GET(self) -> None:  # noqa: N802
        write_json(
            self,
            200,
            {"status": "ok", "service": os.environ.get("SERVICE_NAME", "fixture-service")},
        )


class ProviderHandler(QuietHandler):
    def do_GET(self) -> None:  # noqa: N802
        self._reply()

    def do_POST(self) -> None:  # noqa: N802
        self._reply()

    def _reply(self) -> None:
        if self.path.split("?", 1)[0] in {"/health", "/healthz/ready"}:
            write_json(self, 200, {"status": "ready", "service": "contract-echo-provider"})
            return
        trusted = self.headers.get("x-ojos-caller-service", "")
        if trusted != "contract-echo-consumer":
            write_json(self, 403, {"error": "trusted caller projection is missing"})
            return
        write_json(
            self,
            200,
            {
                "provider": "contract-echo-provider",
                "caller": trusted,
                "path": self.path,
                "value": "cross-engine-binding-ok",
            },
        )


class StorageHeadProvenanceMissHandler(QuietHandler):
    """Healthy compatible provider whose object HEAD is deliberately unproven.

    This fixture exists only for the production-equivalent failure-recovery
    gate.  It implements the declared ``storage.object.head`` API, but an
    object request returns a plain 404 without ``X-OJOS-Storage-Result``.  The
    Problem service must therefore quarantine the cleanup intent rather than
    interpreting the response as authoritative object absence.
    """

    def do_GET(self) -> None:  # noqa: N802
        if self.path.split("?", 1)[0] in {"/health", "/healthz/ready"}:
            write_json(
                self,
                200,
                {
                    "status": "ready",
                    "service": "storage-head-provenance-miss-provider",
                },
            )
            return
        write_json(self, 404, {"status": "not_found"})

    def do_HEAD(self) -> None:  # noqa: N802
        path = self.path.split("?", 1)[0]
        if path in {"/health", "/healthz/ready"}:
            self.send_response(200)
            self.send_header("content-length", "0")
            self.end_headers()
            return
        # Deliberately omit X-OJOS-Storage-Result.  A route miss and an
        # unproven provider 404 must never be accepted as object absence.
        self.send_response(404)
        self.send_header("content-length", "0")
        self.end_headers()


class ManagedConsumerState:
    lock = threading.Lock()
    result: dict[str, Any] | None = None
    error = "waiting for manifest-generated echo binding"
    success_count = 0
    context_generation = 0


class ManagedConsumerHandler(QuietHandler):
    def do_GET(self) -> None:  # noqa: N802
        path = self.path.split("?", 1)[0]
        with ManagedConsumerState.lock:
            result = ManagedConsumerState.result
            error = ManagedConsumerState.error
            success_count = ManagedConsumerState.success_count
            generation = ManagedConsumerState.context_generation
        if path in {"/health", "/healthz/ready"}:
            if result is None:
                write_json(self, 503, {"status": "starting", "error": error})
            else:
                write_json(self, 200, {"status": "ready", "binding": "echo"})
            return
        if path == "/result":
            if result is None:
                write_json(
                    self,
                    503,
                    {
                        "status": "pending",
                        "error": error,
                        "success_count": success_count,
                        "context_generation": generation,
                    },
                )
            else:
                write_json(
                    self,
                    200,
                    {
                        "status": "ok",
                        "binding": "echo",
                        "response": result,
                        "last_error": error,
                        "success_count": success_count,
                        "context_generation": generation,
                    },
                )
            return
        write_json(self, 404, {"status": "not_found"})


class PermissionHandler(QuietHandler):
    def do_GET(self) -> None:  # noqa: N802
        write_json(self, 200, {"status": "ok", "service": "permission-fixture"})

    def do_POST(self) -> None:  # noqa: N802
        if self.headers.get("authorization", "") != "Bearer fixture-permission-token":
            write_json(self, 401, {"code": 401, "msg": "permission fixture token required"})
            return
        _ = read_json_body(self)
        write_json(self, 200, {"code": 0, "msg": "success", "data": {"allowed": True}})


class SnapshotHandler(QuietHandler):
    route_table: dict[str, Any] = {}

    def do_GET(self) -> None:  # noqa: N802
        if self.headers.get("x-ojos-orchestrator-token", "") != "fixture-orchestrator-token":
            write_json(self, 401, {"code": 401, "msg": "orchestrator token required"})
            return
        if not self.path.startswith("/internal/orchestrator/nodes/") or not self.path.endswith(
            "/routes?include_upstream=true"
        ):
            write_json(self, 404, {"code": 404, "msg": "snapshot route not found"})
            return
        write_json(self, 200, {"code": 0, "msg": "success", "data": self.route_table})


class TLSProxyHandler(QuietHandler):
    upstream = ""
    protocol_version = "HTTP/1.1"
    capture_paths: tuple[str, ...] = ()
    capture_lock = threading.Lock()
    captures: list[dict[str, Any]] = []
    capture_sequence = 0

    @classmethod
    def _capture_matches(cls, request_path: str) -> bool:
        path = request_path.split("?", 1)[0]
        return any(
            path.startswith(pattern[:-1])
            if pattern.endswith("*")
            else path == pattern or path.endswith(pattern)
            for pattern in cls.capture_paths
        )

    def do_GET(self) -> None:  # noqa: N802
        self._proxy()

    def do_HEAD(self) -> None:  # noqa: N802
        self._proxy()

    def do_POST(self) -> None:  # noqa: N802
        self._proxy()

    def do_PUT(self) -> None:  # noqa: N802
        self._proxy()

    def do_DELETE(self) -> None:  # noqa: N802
        self._proxy()

    def _write_proxy_response_chunk(self, chunk: bytes, *, chunked: bool) -> None:
        if chunked:
            self.wfile.write(f"{len(chunk):X}\r\n".encode("ascii"))
            self.wfile.write(chunk)
            self.wfile.write(b"\r\n")
        else:
            self.wfile.write(chunk)
        self.wfile.flush()

    def _finish_proxy_response(self, *, chunked: bool) -> None:
        if chunked:
            self.wfile.write(b"0\r\n\r\n")
            self.wfile.flush()

    def _proxy(self) -> None:
        if self.path.split("?", 1)[0] == "/__fixture/proxy-evidence":
            if self.headers.get("x-fixture-control", "") != CONTROL_TOKEN:
                write_json(self, 403, {"error": "fixture control token required"})
                return
            with self.capture_lock:
                captures = json.loads(json.dumps(self.captures))
            write_json(self, 200, {"captures": captures})
            return
        size = int(self.headers.get("content-length", "0"))
        if size < 0 or size > 64 * 1024 * 1024:
            write_json(self, 413, {"error": "request is too large"})
            return
        parsed = urlsplit(self.upstream)
        if parsed.scheme != "http" or not parsed.hostname:
            write_json(self, 500, {"error": "TLS proxy upstream must be an internal HTTP origin"})
            return
        connection = http.client.HTTPConnection(parsed.hostname, parsed.port or 80, timeout=310)
        capture = self._capture_matches(self.path)
        request_hash = hashlib.sha256() if capture else None
        request_capture = bytearray()
        try:
            upstream_path = parsed.path.rstrip("/") + self.path
            connection.putrequest(self.command, upstream_path, skip_host=True, skip_accept_encoding=True)
            connection.putheader("Host", parsed.netloc)
            for key, value in self.headers.items():
                if key.lower() not in {"host", "connection", "content-length", "transfer-encoding"}:
                    connection.putheader(key, value)
            if size:
                connection.putheader("Content-Length", str(size))
            connection.endheaders()
            remaining = size
            while remaining:
                chunk = self.rfile.read(min(64 * 1024, remaining))
                if not chunk:
                    raise ConnectionError("client closed before request body completed")
                if request_hash is not None:
                    request_hash.update(chunk)
                    if len(request_capture) < 1024 * 1024:
                        request_capture.extend(chunk[: 1024 * 1024 - len(request_capture)])
                connection.send(chunk)
                remaining -= len(chunk)
            response = connection.getresponse()
        except Exception as exc:
            connection.close()
            write_json(self, 502, {"error": f"TLS proxy upstream failed: {exc}"})
            return
        try:
            self.send_response(response.status)
            content_length = response.getheader("content-length")
            response_has_body = self.command != "HEAD" and not (
                100 <= response.status < 200 or response.status in {204, 304}
            )
            downstream_chunked = response_has_body and content_length is None
            for key, value in response.headers.items():
                if key.lower() not in {"connection", "transfer-encoding", "content-length"}:
                    self.send_header(key, value)
            if content_length is not None:
                self.send_header("content-length", content_length)
            elif downstream_chunked:
                # http.client decodes an upstream chunked response. Re-encode
                # the decoded bytes for the downstream HTTP/1.1 connection so
                # a successful response ends with a protocol boundary instead
                # of relying on a TLS socket close.
                self.send_header("transfer-encoding", "chunked")
            self.end_headers()
            if response_has_body:
                try:
                    if capture:
                        response_hash = hashlib.sha256()
                        response_capture = bytearray()
                        response_size = 0
                        while True:
                            chunk = response.read(64 * 1024)
                            if not chunk:
                                break
                            response_hash.update(chunk)
                            response_size += len(chunk)
                            if len(response_capture) < 1024 * 1024:
                                response_capture.extend(
                                    chunk[: 1024 * 1024 - len(response_capture)]
                                )
                            self._write_proxy_response_chunk(chunk, chunked=downstream_chunked)
                        self._finish_proxy_response(chunked=downstream_chunked)
                        decoded_request: Any = None
                        if size and size <= 1024 * 1024:
                            try:
                                decoded_request = json.loads(bytes(request_capture))
                            except (UnicodeDecodeError, json.JSONDecodeError):
                                decoded_request = None
                        try:
                            decoded: Any = (
                                json.loads(bytes(response_capture))
                                if response_size <= 1024 * 1024
                                else {
                                    "non_json_sha256": "sha256:" + response_hash.hexdigest(),
                                    "size_bytes": response_size,
                                }
                            )
                        except (UnicodeDecodeError, json.JSONDecodeError):
                            decoded = {
                                "non_json_sha256": "sha256:" + response_hash.hexdigest(),
                                "size_bytes": response_size,
                            }
                        with self.capture_lock:
                            type(self).capture_sequence += 1
                            self.captures.append(
                                {
                                    "sequence": type(self).capture_sequence,
                                    "captured_at_unix_ms": int(time.time() * 1000),
                                    "method": self.command,
                                    "path": self.path,
                                    "status": response.status,
                                    "request_headers": {
                                        key: self.headers.get(key, "")
                                        for key in (
                                            "prefer",
                                            "content-type",
                                            "idempotency-key",
                                        )
                                        if self.headers.get(key) is not None
                                    },
                                    "request_size_bytes": size,
                                    "request_sha256": "sha256:" + request_hash.hexdigest()
                                    if request_hash is not None
                                    else "",
                                    "request_body": decoded_request,
                                    "body": decoded,
                                    "response_size_bytes": response_size,
                                    "response_sha256": "sha256:" + response_hash.hexdigest(),
                                }
                            )
                            # Bounded, but large enough to retain one complete
                            # claim/download/result exchange under heartbeat noise.
                            del self.captures[:-128]
                    else:
                        while True:
                            chunk = response.read(64 * 1024)
                            if not chunk:
                                break
                            self._write_proxy_response_chunk(chunk, chunked=downstream_chunked)
                        self._finish_proxy_response(chunked=downstream_chunked)
                except Exception:
                    # A chunked response without the terminating zero chunk is
                    # deliberately incomplete. Close this downstream connection
                    # so clients reject a truncated upstream body.
                    self.close_connection = True
                    raise
        finally:
            response.close()
            connection.close()


class OIDCHandler(QuietHandler):
    issuer = ""
    jwk: dict[str, str] = {}

    def do_GET(self) -> None:  # noqa: N802
        path = self.path.split("?", 1)[0]
        if path in {"/healthz/ready", "/health"}:
            write_json(self, 200, {"status": "ready", "service": "oidc-fixture"})
            return
        if path == "/.well-known/openid-configuration":
            write_json(
                self,
                200,
                {
                    "issuer": self.issuer,
                    "jwks_uri": self.issuer + "/jwks.json",
                    "authorization_endpoint": self.issuer + "/authorize",
                    "token_endpoint": self.issuer + "/token",
                    "id_token_signing_alg_values_supported": ["RS256"],
                },
            )
            return
        if path == "/jwks.json":
            write_json(self, 200, {"keys": [self.jwk]})
            return
        if path == "/authorize":
            write_json(self, 400, {"error": "interactive authorization is not used by this gate"})
            return
        write_json(self, 404, {"error": "OIDC fixture route not found"})

    def do_POST(self) -> None:  # noqa: N802
        if self.path.split("?", 1)[0] == "/token":
            write_json(self, 400, {"error": "invalid_grant"})
            return
        write_json(self, 404, {"error": "OIDC fixture route not found"})


class QuietStaticHandler(SimpleHTTPRequestHandler):
    server_version = "ojos-cross-machine-static/1"

    def log_message(self, fmt: str, *args: Any) -> None:
        print(fmt % args, flush=True)

    def end_headers(self) -> None:
        self.send_header("cache-control", "no-store")
        super().end_headers()


class GatewayHandler(QuietHandler):
    routes: dict[str, dict[str, Any]] = {}
    workload_token = DEFAULT_WORKLOAD_TOKEN

    def do_GET(self) -> None:  # noqa: N802
        self._handle()

    def do_HEAD(self) -> None:  # noqa: N802
        self._handle()

    def do_POST(self) -> None:  # noqa: N802
        self._handle()

    def _control_allowed(self) -> bool:
        return self.headers.get("x-fixture-control", "") == CONTROL_TOKEN

    def _workload_allowed(self) -> bool:
        if self.headers.get("authorization", "") != "Bearer " + self.workload_token:
            write_json(self, 401, {"error": "deployment workload token required"})
            return False
        with STATE.lock:
            STATE.workload_requests += 1
            if any(name.lower() in FORGED_IDENTITY_HEADERS for name in self.headers):
                STATE.identity_headers_removed = False
        return True

    def _handle(self) -> None:
        path = self.path.split("?", 1)[0]
        if path == "/healthz/ready":
            write_json(self, 200, {"status": "ready", "gateway": "a"})
            return
        if path == "/fixture/problem" and self.command == "POST":
            if not self._control_allowed():
                write_json(self, 403, {"error": "fixture control token required"})
                return
            try:
                write_json(self, 201, STATE.create_problem())
            except ValueError as exc:
                write_json(self, 409, {"error": str(exc)})
            return
        if path == "/fixture/submission" and self.command == "POST":
            if not self._control_allowed():
                write_json(self, 403, {"error": "fixture control token required"})
                return
            try:
                write_json(self, 202, STATE.create_submission())
            except ValueError as exc:
                write_json(self, 409, {"error": str(exc)})
            return
        if path == "/fixture/evidence" and self.command == "GET":
            if not self._control_allowed():
                write_json(self, 403, {"error": "fixture control token required"})
                return
            write_json(self, 200, STATE.evidence())
            return

        route = self._match_route(path)
        if route is None:
            write_json(self, 404, {"error": "no applied ApiBinding route"})
            return
        if not self._workload_allowed():
            return
        suffix = path[len(route[0]) :]
        config = route[1]
        kind = config.get("kind")
        if kind == "judge":
            self._judge(suffix)
        elif kind == "storage":
            self._storage(suffix)
        elif kind == "proxy":
            self._proxy(config, suffix)
        else:
            write_json(self, 503, {"error": "binding provider kind is unavailable"})

    def _match_route(self, path: str) -> tuple[str, dict[str, Any]] | None:
        for prefix in sorted(self.routes, key=len, reverse=True):
            if path == prefix or path.startswith(prefix + "/"):
                return prefix, self.routes[prefix]
        return None

    def _judge(self, suffix: str) -> None:
        if suffix == "/register" and self.command == "POST":
            body = read_json_body(self)
            write_json(
                self,
                200,
                {
                    "worker_id": body.get("worker_id", ""),
                    "lease_ttl_seconds": 60,
                    "status": "ONLINE",
                },
            )
            return
        if suffix == "/heartbeat" and self.command == "POST":
            write_json(self, 200, {})
            return
        if suffix == "/tasks/claim" and self.command == "POST":
            started = time.monotonic()
            prefer = self.headers.get("prefer", "")
            time.sleep(0.3)
            with STATE.lock:
                STATE.claim_prefer = prefer
                STATE.claim_wait_ms = int((time.monotonic() - started) * 1000)
                tasks: list[dict[str, Any]] = []
                if STATE.task is not None and STATE.task_state == "queued":
                    STATE.task_state = "leased"
                    STATE.transitions.append("worker.long_poll_claimed")
                    tasks = [STATE.task]
            write_json(self, 200, {"tasks": tasks})
            return
        if suffix.startswith("/tasks/") and suffix.endswith("/heartbeat"):
            write_json(self, 200, {})
            return
        if suffix.startswith("/tasks/") and suffix.endswith("/result") and self.command == "POST":
            body = read_json_body(self)
            with STATE.lock:
                STATE.result = body
                STATE.task_state = "succeeded"
                STATE.transitions.append("worker.result_reported")
                STATE.transitions.append("judge.submission_completed")
            write_json(self, 200, {"accepted": True, "status": body.get("status", "")})
            return
        if suffix.startswith("/tasks/") and suffix.endswith("/fail") and self.command == "POST":
            body = read_json_body(self)
            with STATE.lock:
                STATE.result = body
                STATE.task_state = "failed"
                STATE.transitions.append("worker.failure_reported")
            write_json(self, 200, {})
            return
        write_json(self, 404, {"error": "unknown judge worker operation"})

    def _storage(self, suffix: str) -> None:
        with STATE.lock:
            data = STATE.objects.get(suffix)
        if data is None:
            write_json(self, 404, {"error": "object not found"})
            return
        self.send_response(200)
        self.send_header("content-type", "application/octet-stream")
        self.send_header("content-length", str(len(data)))
        self.send_header("x-ojos-sha256", sha256_prefixed(data))
        self.end_headers()
        if self.command != "HEAD":
            for offset in range(0, len(data), 16384):
                self.wfile.write(data[offset : offset + 16384])

    def _proxy(self, config: dict[str, Any], suffix: str) -> None:
        upstream = str(config.get("upstream", "")).rstrip("/")
        if not upstream.startswith("http://"):
            write_json(self, 503, {"error": "fixture upstream must be an internal HTTP URL"})
            return
        request = urllib.request.Request(
            upstream + suffix,
            method=self.command,
            headers={"x-ojos-caller-service": str(config.get("consumer_service", ""))},
        )
        try:
            with urllib.request.urlopen(request, timeout=5) as response:
                body = response.read(1024 * 1024)
                status = response.status
                content_type = response.headers.get("content-type", "application/octet-stream")
        except Exception as exc:  # pragma: no cover - exercised by live negative injection
            write_json(self, 502, {"error": str(exc)})
            return
        with STATE.lock:
            STATE.third_party_calls += 1
        self.send_response(status)
        self.send_header("content-type", content_type)
        self.send_header("content-length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def ensure_tls(directory: Path) -> tuple[Path, Path]:
    configured_cert = os.environ.get("TLS_CERT_FILE", "").strip()
    configured_key = os.environ.get("TLS_KEY_FILE", "").strip()
    if configured_cert or configured_key:
        if not configured_cert or not configured_key:
            raise ValueError("TLS_CERT_FILE and TLS_KEY_FILE must be configured together")
        cert, key = Path(configured_cert), Path(configured_key)
        if not cert.is_file() or not key.is_file():
            raise ValueError("configured TLS certificate or key is missing")
        return cert, key
    directory.mkdir(parents=True, exist_ok=True)
    cert = directory / "ca.pem"
    key = directory / "gateway.key"
    if cert.exists() and key.exists():
        return cert, key
    gateway_ip = os.environ.get("GATEWAY_IP", "").strip()
    subject_alt_name = "subjectAltName=DNS:gateway-a,IP:127.0.0.1"
    if gateway_ip:
        # GATEWAY_IP is supplied by the harness from Docker inspect and is not
        # accepted from a release or workload.
        socket.inet_aton(gateway_ip)
        subject_alt_name += ",IP:" + gateway_ip
    subprocess.run(
        [
            "openssl",
            "req",
            "-x509",
            "-newkey",
            "ed25519",
            "-nodes",
            "-keyout",
            str(key),
            "-out",
            str(cert),
            "-days",
            "2",
            "-subj",
            "/CN=gateway-a",
            "-addext",
            subject_alt_name,
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return cert, key


def serve_gateway(port: int) -> None:
    raw_routes = json.loads(os.environ["BINDINGS_JSON"])
    if not isinstance(raw_routes, list) or not raw_routes:
        raise SystemExit("BINDINGS_JSON must contain at least one route")
    GatewayHandler.routes = {str(item["base_path"]): item for item in raw_routes}
    GatewayHandler.workload_token = os.environ.get("WORKLOAD_TOKEN", DEFAULT_WORKLOAD_TOKEN)
    cert, key = ensure_tls(Path("/tmp/ojos-fixture-tls"))
    server = ThreadingHTTPServer(("0.0.0.0", port), GatewayHandler)
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(str(cert), str(key))
    server.socket = context.wrap_socket(server.socket, server_side=True)
    print(canonical_json({"status": "ready", "role": "gateway", "port": port}).decode(), flush=True)
    server.serve_forever()


def serve_tls_proxy(port: int) -> None:
    TLSProxyHandler.upstream = os.environ["UPSTREAM_URL"]
    raw_capture_paths = json.loads(os.environ.get("CAPTURE_PATHS_JSON", "[]"))
    if not isinstance(raw_capture_paths, list) or not all(
        isinstance(path, str) and path.startswith("/") for path in raw_capture_paths
    ):
        raise ValueError("CAPTURE_PATHS_JSON must be a JSON array of absolute path suffixes")
    TLSProxyHandler.capture_paths = tuple(raw_capture_paths)
    TLSProxyHandler.captures = []
    TLSProxyHandler.capture_sequence = 0
    cert, key = ensure_tls(Path("/tmp/ojos-fixture-tls"))
    server = ThreadingHTTPServer(("0.0.0.0", port), TLSProxyHandler)
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(str(cert), str(key))
    server.socket = context.wrap_socket(server.socket, server_side=True)
    print(canonical_json({"status": "ready", "role": "tls-proxy", "port": port}).decode(), flush=True)
    server.serve_forever()


def _base64url_unsigned(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode("ascii").rstrip("=")


def _generated_rsa_jwk(directory: Path) -> dict[str, str]:
    directory.mkdir(parents=True, exist_ok=True)
    key = directory / "oidc-rsa.pem"
    subprocess.run(
        ["openssl", "genpkey", "-algorithm", "RSA", "-pkeyopt", "rsa_keygen_bits:2048", "-out", str(key)],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    modulus = subprocess.run(
        ["openssl", "rsa", "-in", str(key), "-noout", "-modulus"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    prefix = "Modulus="
    if not modulus.startswith(prefix):
        raise ValueError("openssl did not return an RSA modulus")
    number = int(modulus[len(prefix) :], 16)
    raw = number.to_bytes((number.bit_length() + 7) // 8, "big")
    return {
        "kty": "RSA",
        "kid": "cross-machine-oidc-1",
        "use": "sig",
        "alg": "RS256",
        "n": _base64url_unsigned(raw),
        "e": _base64url_unsigned((65537).to_bytes(3, "big")),
    }


def serve_oidc(port: int) -> None:
    issuer = os.environ.get("OIDC_ISSUER", "").strip().rstrip("/")
    if not issuer.startswith("https://"):
        raise ValueError("OIDC_ISSUER must be an HTTPS origin")
    OIDCHandler.issuer = issuer
    OIDCHandler.jwk = _generated_rsa_jwk(Path("/tmp/ojos-fixture-oidc"))
    cert, key = ensure_tls(Path("/tmp/ojos-fixture-tls"))
    server = ThreadingHTTPServer(("0.0.0.0", port), OIDCHandler)
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(str(cert), str(key))
    server.socket = context.wrap_socket(server.socket, server_side=True)
    print(canonical_json({"status": "ready", "role": "oidc", "port": port}).decode(), flush=True)
    server.serve_forever()


def serve_static_tls(port: int) -> None:
    root = Path(os.environ.get("STATIC_ROOT", "")).resolve()
    if not root.is_dir():
        raise ValueError("STATIC_ROOT must name an existing directory")
    cert, key = ensure_tls(Path("/tmp/ojos-fixture-tls"))
    server = ThreadingHTTPServer(
        ("0.0.0.0", port), partial(QuietStaticHandler, directory=str(root))
    )
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(str(cert), str(key))
    server.socket = context.wrap_socket(server.socket, server_side=True)
    print(canonical_json({"status": "ready", "role": "static-tls", "port": port}).decode(), flush=True)
    server.serve_forever()


def load_context(path: Path) -> tuple[dict[str, Any], str, ssl.SSLContext]:
    context = json.loads(path.read_text(encoding="utf-8"))
    token_path = Path(context["credential_file"])
    token = token_path.read_text(encoding="utf-8").strip()
    if not token or any(character.isspace() for character in token):
        raise ValueError("workload credential is invalid")
    if any(key in context for key in ("token", "admin_token", "management_token")):
        raise ValueError("service context embedded a credential")
    ca_file = context.get("gateway", {}).get("ca_file")
    tls = ssl.create_default_context(cafile=ca_file)
    return context, token, tls


def binding_url(context: dict[str, Any], name: str, relative: str = "") -> str:
    binding = context["bindings"][name]
    relative = "/" + relative.lstrip("/") if relative else ""
    return context["gateway"]["origin"].rstrip("/") + binding["base_path"].rstrip("/") + relative


def binding_head(
    context_path: Path,
    binding_name: str,
    relative_path: str,
    expected_deployment_id: str,
) -> dict[str, Any]:
    """Issue one bounded HEAD through an Agent-materialized ApiBinding.

    This probe is intentionally a workload, not a management client: its only
    inputs are the mounted Service Context, its sibling credential/CA files,
    the requirement name, and a provider-relative path.  The returned JSON is
    deliberately limited to non-secret response metadata.
    """

    parsed = urlsplit(relative_path)
    decoded_path = parsed.path
    for _ in range(2):
        decoded_path = unquote(decoded_path)
    if (
        not relative_path.startswith("/")
        or parsed.scheme
        or parsed.netloc
        or parsed.query
        or parsed.fragment
        or any(segment == ".." for segment in decoded_path.split("/"))
    ):
        raise ValueError("binding HEAD relative path is invalid")
    raw_context = json.loads(context_path.read_text(encoding="utf-8"))
    deployment = raw_context.get("deployment", {})
    gateway = raw_context.get("gateway", {})
    binding = raw_context.get("bindings", {}).get(binding_name)
    origin = str(gateway.get("origin", ""))
    parsed_origin = urlsplit(origin)
    generation = raw_context.get("generation")
    if (
        raw_context.get("schema_version") != 1
        or deployment.get("id") != expected_deployment_id
        or deployment.get("service") != "problem-service"
        or not str(deployment.get("node", "")).strip()
        or isinstance(generation, bool)
        or not isinstance(generation, int)
        or generation < 1
        or parsed_origin.scheme != "https"
        or not parsed_origin.hostname
        or parsed_origin.username is not None
        or parsed_origin.password is not None
        or parsed_origin.path not in ("", "/")
        or parsed_origin.query
        or parsed_origin.fragment
        or gateway.get("ca_file") != "/run/ojos/service/ca.pem"
        or raw_context.get("credential_file") != "/run/ojos/service/token"
    ):
        raise ValueError("binding HEAD requires the expected managed Problem Service Context")
    if (
        not isinstance(binding, dict)
        or not str(binding.get("binding_id", "")).strip()
        or binding.get("api_id") != "storage.object.head"
        or binding.get("base_path") != "/internal/apis/storage.object.head"
        or isinstance(binding.get("timeout_ms"), bool)
        or not isinstance(binding.get("timeout_ms"), int)
        or not 1 <= int(binding["timeout_ms"]) <= 300_000
    ):
        raise ValueError("binding HEAD requires a storage.object.head ApiBinding")
    context, token, tls = load_context(context_path)
    request = urllib.request.Request(
        binding_url(context, binding_name, relative_path),
        method="HEAD",
        headers={"authorization": "Bearer " + token},
    )

    def result(status: int, headers: Any) -> dict[str, Any]:
        raw_size = str(headers.get("Content-Length", "")).strip()
        try:
            size_bytes = int(raw_size) if raw_size else -1
        except ValueError:
            size_bytes = -1
        return {
            "status": int(status),
            "sha256_header": str(headers.get("X-OJOS-Object-Sha256", "")).strip(),
            "size_bytes": size_bytes,
            "storage_result_header": str(
                headers.get("X-OJOS-Storage-Result", "")
            ).strip(),
        }

    opener = urllib.request.build_opener(
        urllib.request.ProxyHandler({}),
        NoRedirectHandler(),
        urllib.request.HTTPSHandler(context=tls),
    )
    try:
        with opener.open(request, timeout=BINDING_HEAD_TIMEOUT_SECONDS) as response:
            return result(response.status, response.headers)
    except urllib.error.HTTPError as error:
        try:
            return result(error.code, error.headers)
        finally:
            error.close()


def http_json(
    url: str,
    token: str,
    tls: ssl.SSLContext,
    method: str = "GET",
    value: Any | None = None,
    headers: dict[str, str] | None = None,
) -> Any:
    body = canonical_json(value) if value is not None else None
    request_headers = {"authorization": "Bearer " + token}
    if body is not None:
        request_headers["content-type"] = "application/json"
    request_headers.update(headers or {})
    request = urllib.request.Request(url, data=body, method=method, headers=request_headers)
    with urllib.request.urlopen(request, context=tls, timeout=40) as response:
        return json.loads(response.read())


def verified_download(
    context: dict[str, Any], token: str, tls: ssl.SSLContext, reference: dict[str, Any]
) -> bytes:
    if reference.get("url"):
        raise ValueError("managed ApiResourceRef must not contain a URL")
    binding = str(reference["binding"])
    declared = context["bindings"][binding]
    if declared["api_id"] != reference["api_id"]:
        raise ValueError("ApiResourceRef does not match its named binding")
    relative = str(reference["relative_path"])
    if not relative.startswith("/") or "://" in relative or "/../" in relative:
        raise ValueError("ApiResourceRef relative path is invalid")
    request = urllib.request.Request(
        binding_url(context, binding, relative),
        method="GET",
        headers={"authorization": "Bearer " + token},
    )
    digest = hashlib.sha256()
    chunks: list[bytes] = []
    size = 0
    with urllib.request.urlopen(request, context=tls, timeout=40) as response:
        while True:
            chunk = response.read(16384)
            if not chunk:
                break
            size += len(chunk)
            if size > int(reference["size_bytes"]):
                raise ValueError("resource exceeded advertised size")
            digest.update(chunk)
            chunks.append(chunk)
    expected_digest = str(reference["sha256"]).removeprefix("sha256:")
    if size != int(reference["size_bytes"]) or digest.hexdigest() != expected_digest:
        raise ValueError("resource digest or size mismatch")
    return b"".join(chunks)


def fixture_worker(context_path: Path) -> None:
    context, token, tls = load_context(context_path)
    deployment_id = context["deployment"]["id"]
    register = http_json(
        binding_url(context, "judge_control", "/register"),
        token,
        tls,
        "POST",
        {
            "worker_id": deployment_id,
            "worker_name": "cross-engine-fixture-worker",
            "hostname": socket.gethostname(),
            "version": "fixture-v2",
            "capabilities": ["contract-v2"],
            "supported_languages": ["cpp17"],
            "max_concurrency": 1,
        },
    )
    if register.get("worker_id") != deployment_id:
        raise ValueError("worker registration identity was changed")
    http_json(
        binding_url(context, "judge_control", "/heartbeat"),
        token,
        tls,
        "POST",
        {"worker_id": deployment_id, "running_tasks": [], "running_count": 0, "available_slots": 1},
    )
    claimed = http_json(
        binding_url(context, "judge_control", "/tasks/claim"),
        token,
        tls,
        "POST",
        {
            "worker_id": deployment_id,
            "capabilities": ["contract-v2"],
            "supported_languages": ["cpp17"],
            "available_slots": 1,
        },
        {"Prefer": "wait=25"},
    )
    tasks = claimed.get("tasks", [])
    if len(tasks) != 1:
        raise ValueError(f"expected one task, received {len(tasks)}")
    task = tasks[0]
    source = verified_download(context, token, tls, task["source"])
    package = verified_download(context, token, tls, task["problem_package"])
    with zipfile.ZipFile(io.BytesIO(package)) as archive:
        if "problem.yaml" not in archive.namelist():
            raise ValueError("problem artifact is not a problem package")
    if b"int main" not in source:
        raise ValueError("source artifact is not the frozen submission source")
    result = http_json(
        binding_url(context, "judge_control", f"/tasks/{task['task_id']}/result"),
        token,
        tls,
        "POST",
        {
            "worker_id": deployment_id,
            "lease_version": task["lease_version"],
            "status": "ACCEPTED",
            "score": 100,
            "time_ms": 1,
            "memory_kb": 1024,
            "message": "fixture worker verified both binding resources",
            "cases": [],
        },
    )
    if not result.get("accepted"):
        raise ValueError("Judge API did not accept the result")
    print(
        canonical_json(
            {
                "status": "ok",
                "deployment_id": deployment_id,
                "source_sha256": sha256_prefixed(source),
                "package_sha256": sha256_prefixed(package),
                "task_resource_urls_empty": not task["source"].get("url")
                and not task["problem_package"].get("url"),
            }
        ).decode(),
        flush=True,
    )


def generic_consumer(context_path: Path) -> None:
    context, token, tls = load_context(context_path)
    value = http_json(binding_url(context, "echo"), token, tls)
    if value.get("value") != "cross-engine-binding-ok":
        raise ValueError(f"unexpected provider response: {value!r}")
    print(canonical_json({"status": "ok", "binding": "echo", "response": value}).decode(), flush=True)


def managed_consumer_service(context_path: Path, port: int) -> None:
    """Long-lived generic consumer used by the strict Store/Agent gate.

    The process knows only the requirement name from its own Release.  It has
    no Gateway URL, provider address, token, deployment ID, or Orchestrator
    product hook; those are all read from the Agent materialized context.
    """

    def consume() -> None:
        while True:
            try:
                context, token, tls = load_context(context_path)
                value = http_json(binding_url(context, "echo"), token, tls)
                if value.get("value") != "cross-engine-binding-ok":
                    raise ValueError(f"unexpected provider response: {value!r}")
                permission = None
                if "permission_check" in context.get("bindings", {}):
                    permission = http_json(
                        binding_url(context, "permission_check"),
                        token,
                        tls,
                        method="POST",
                        value={
                            "user_id": 1,
                            "permission": "problem.view",
                            "scope_type": "global",
                            "scope_id": 0,
                        },
                    )
                    allowed = permission.get("data", permission).get("allowed")
                    if allowed is not True:
                        raise ValueError(
                            f"workload permission_check binding rejected known admin: {permission!r}"
                        )
                with ManagedConsumerState.lock:
                    ManagedConsumerState.result = {**value, "permission_check": permission}
                    ManagedConsumerState.error = ""
                    ManagedConsumerState.success_count += 1
                    ManagedConsumerState.context_generation = int(
                        context.get("generation", 0)
                    )
                print(
                    canonical_json({"status": "ok", "binding": "echo", "response": value}).decode(),
                    flush=True,
                )
                time.sleep(0.5)
            except Exception as exc:  # retry while the staged route becomes active
                with ManagedConsumerState.lock:
                    ManagedConsumerState.error = str(exc)[:512]
                time.sleep(0.25)

    threading.Thread(target=consume, name="managed-generic-consumer", daemon=True).start()
    ThreadingHTTPServer(("0.0.0.0", port), ManagedConsumerHandler).serve_forever()


def probe_agent() -> None:
    targets = json.loads(os.environ["AGENT_TARGETS_JSON"])
    ca_file = os.environ.get("AGENT_CA_FILE", "").strip()
    tls = ssl.create_default_context(cafile=ca_file) if ca_file else None
    opener = urllib.request.build_opener(
        urllib.request.ProxyHandler({}),
        *([urllib.request.HTTPSHandler(context=tls)] if tls is not None else []),
    )
    results = []
    for target in targets:
        request = urllib.request.Request(target["url"], method="GET")
        with opener.open(request, timeout=5) as response:
            results.append({"name": target["name"], "status": response.status})
    print(canonical_json({"status": "ok", "targets": results}).decode(), flush=True)


def probe_boundary() -> None:
    targets = json.loads(os.environ["DENIED_TARGETS_JSON"])
    results = []
    for target in targets:
        denied = False
        error = ""
        try:
            with socket.create_connection((target["host"], int(target["port"])), timeout=1):
                pass
        except OSError as exc:
            denied = True
            error = type(exc).__name__
        if not denied:
            raise ValueError(f"business workload reached forbidden target {target['name']}")
        results.append({"name": target["name"], "denied": True, "error": error})
    print(canonical_json({"status": "ok", "denied": results}).decode(), flush=True)


def probe_connectivity() -> None:
    targets = json.loads(os.environ["CONNECT_TARGETS_JSON"])
    results = []
    for target in targets:
        started = time.monotonic()
        with socket.create_connection((target["host"], int(target["port"])), timeout=5):
            pass
        results.append(
            {
                "name": target["name"],
                "connected": True,
                "elapsed_ms": int((time.monotonic() - started) * 1000),
            }
        )
    print(canonical_json({"status": "ok", "targets": results}).decode(), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "role",
        choices=[
            "gateway",
            "service",
            "provider",
            "storage-head-provenance-miss",
            "permission",
            "snapshot",
            "tls-proxy",
            "oidc",
            "static-tls",
            "worker",
            "consumer",
            "consumer-service",
            "binding-head",
            "agent-probe",
            "boundary-probe",
            "connect-probe",
            "noop",
        ],
    )
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--context", type=Path, default=Path("/run/ojos/service/context.json"))
    parser.add_argument("--binding", default="")
    parser.add_argument("--relative-path", default="")
    parser.add_argument("--deployment", default="")
    args = parser.parse_args()
    if args.role == "gateway":
        serve_gateway(args.port)
    elif args.role == "service":
        ThreadingHTTPServer(("0.0.0.0", args.port), PlainServiceHandler).serve_forever()
    elif args.role == "provider":
        ThreadingHTTPServer(("0.0.0.0", args.port), ProviderHandler).serve_forever()
    elif args.role == "storage-head-provenance-miss":
        ThreadingHTTPServer(
            ("0.0.0.0", args.port), StorageHeadProvenanceMissHandler
        ).serve_forever()
    elif args.role == "permission":
        ThreadingHTTPServer(("0.0.0.0", args.port), PermissionHandler).serve_forever()
    elif args.role == "snapshot":
        SnapshotHandler.route_table = json.loads(os.environ["ROUTE_TABLE_JSON"])
        ThreadingHTTPServer(("0.0.0.0", args.port), SnapshotHandler).serve_forever()
    elif args.role == "tls-proxy":
        serve_tls_proxy(args.port)
    elif args.role == "oidc":
        serve_oidc(args.port)
    elif args.role == "static-tls":
        serve_static_tls(args.port)
    elif args.role == "worker":
        fixture_worker(args.context)
    elif args.role == "consumer":
        generic_consumer(args.context)
    elif args.role == "consumer-service":
        managed_consumer_service(args.context, args.port)
    elif args.role == "binding-head":
        if not args.binding or not args.relative_path or not args.deployment:
            parser.error(
                "binding-head requires --binding, --relative-path, and --deployment"
            )
        print(
            canonical_json(
                binding_head(
                    args.context,
                    args.binding,
                    args.relative_path,
                    args.deployment,
                )
            ).decode(),
            flush=True,
        )
    elif args.role == "agent-probe":
        probe_agent()
    elif args.role == "boundary-probe":
        probe_boundary()
    elif args.role == "connect-probe":
        probe_connectivity()
    elif args.role == "noop":
        return


if __name__ == "__main__":
    main()
