// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResp struct {
	Status string `json:"status"`
}

type HealthComponent struct {
	Name    string `json:"name"`
	Status  string `json:"status"`
	Latency int64  `json:"latency_ms"`
	Message string `json:"message,optional"`
}

type AdminHealthResp struct {
	Status            string            `json:"status"`
	Components        []HealthComponent `json:"components"`
	WorkerOnlineCount int64             `json:"worker_online_count"`
	QueuePending      int64             `json:"queue_pending"`
	InternalAuth      string            `json:"internal_auth"`
}

type ModuleSetItem struct {
	SetId       string `json:"set_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	SortOrder   int    `json:"sort_order"`
}

type ModuleNodeItem struct {
	ModuleId    string `json:"module_id"`
	SetId       string `json:"set_id"`
	Name        string `json:"name"`
	Version     string `json:"version"`
	Status      string `json:"status"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
	Manifest    any    `json:"manifest,omitempty"`
}

type ModuleEdgeItem struct {
	FromModuleId      string `json:"from_module_id"`
	ToModuleId        string `json:"to_module_id"`
	EdgeType          string `json:"edge_type"`
	VersionConstraint string `json:"version_constraint"`
	Required          bool   `json:"required"`
}

type ModuleComponentItem struct {
	ModuleId      string `json:"module_id"`
	ComponentId   string `json:"component_id"`
	ComponentType string `json:"component_type"`
	Status        string `json:"status"`
	Config        any    `json:"config"`
}

type ModuleInstallationItem struct {
	ModuleId   string `json:"module_id"`
	Name       string `json:"name"`
	Version    string `json:"version"`
	Status     string `json:"status"`
	Manifest   any    `json:"manifest"`
	EnabledAt  string `json:"enabled_at,omitempty"`
	DisabledAt string `json:"disabled_at,omitempty"`
}

type ModulePermissionItem struct {
	ModuleId      string `json:"module_id"`
	PermissionKey string `json:"permission_key"`
	Description   string `json:"description"`
}

type ModuleMenuItem struct {
	ModuleId           string `json:"module_id"`
	MenuKey            string `json:"menu_key"`
	Title              string `json:"title"`
	RoutePath          string `json:"route_path"`
	Icon               string `json:"icon"`
	ParentKey          string `json:"parent_key"`
	SortOrder          int    `json:"sort_order"`
	RequiredPermission string `json:"required_permission"`
	Enabled            bool   `json:"enabled"`
}

type ModuleFrontendRouteItem struct {
	ModuleId           string `json:"module_id"`
	RoutePath          string `json:"route_path"`
	RouteName          string `json:"route_name"`
	ComponentKey       string `json:"component_key"`
	RequiredPermission string `json:"required_permission"`
	Enabled            bool   `json:"enabled"`
}

type ModuleGatewayRouteItem struct {
	ModuleId      string `json:"module_id"`
	Prefix        string `json:"prefix"`
	TargetService string `json:"target_service"`
	AuthMode      string `json:"auth_mode"`
	Enabled       bool   `json:"enabled"`
}

type ListModulesResp struct {
	Modules []ModuleNodeItem `json:"modules"`
}

type ListModuleSetsResp struct {
	Sets []ModuleSetItem `json:"sets"`
}

type ModuleTopologyResp struct {
	Sets            []ModuleSetItem             `json:"sets"`
	Nodes           []ModuleRuntimeTopologyNode `json:"nodes"`
	Edges           []ModuleRuntimeTopologyEdge `json:"edges"`
	Components      []ModuleComponentItem       `json:"components"`
	ModuleNodes     []ModuleNodeItem            `json:"module_nodes"`
	DependencyEdges []ModuleEdgeItem            `json:"dependency_edges"`
}

type ModuleRuntimeSnapshotResp struct {
	Version        string                      `json:"version"`
	GeneratedAt    string                      `json:"generated_at"`
	Modules        []ModuleNodeItem            `json:"modules"`
	Permissions    []ModulePermissionItem      `json:"permissions"`
	Roles          []ModuleRuntimeManifestItem `json:"roles"`
	Menus          []ModuleMenuItem            `json:"menus"`
	FrontendRoutes []ModuleFrontendRouteItem   `json:"frontend_routes"`
	GatewayRoutes  []ModuleGatewayRouteItem    `json:"gateway_routes"`
	Components     []ModuleRuntimeComponent    `json:"components"`
	Services       []ModuleRuntimeService      `json:"services"`
	Workers        []ModuleRuntimeService      `json:"workers"`
	StorageBuckets []ModuleRuntimeManifestItem `json:"storage_buckets"`
	HealthChecks   []ModuleRuntimeComponent    `json:"health_checks"`
	Operations     []ModuleRuntimeManifestItem `json:"operations"`
	Topology       ModuleRuntimeTopology       `json:"topology"`
	Warnings       []string                    `json:"warnings"`
}

type ModuleRuntimeComponent struct {
	ModuleId    string `json:"module_id"`
	ComponentId string `json:"component_id"`
	Type        string `json:"type"`
	Status      string `json:"status"`
	Config      any    `json:"config"`
}

type ModuleRuntimeService struct {
	ServiceId      string   `json:"service_id"`
	ModuleId       string   `json:"module_id"`
	Name           string   `json:"name"`
	Kind           string   `json:"kind"`
	Lifecycle      string   `json:"lifecycle"`
	Runtime        string   `json:"runtime"`
	ComposeService string   `json:"compose_service,omitempty"`
	State          string   `json:"state"`
	Health         string   `json:"health"`
	Required       bool     `json:"required"`
	Routes         []string `json:"routes"`
	HealthCheckId  string   `json:"health_check_id,omitempty"`
	Status         string   `json:"status"`
	BlockedBy      []string `json:"blocked_by"`
	Warnings       []string `json:"warnings"`
}

type ModuleRuntimeManifestItem struct {
	ModuleId string `json:"module_id"`
	Id       string `json:"id"`
	Type     string `json:"type"`
	Status   string `json:"status"`
	Enabled  bool   `json:"enabled"`
	Config   any    `json:"config"`
}

type ModuleRuntimeTopology struct {
	Nodes           []ModuleRuntimeTopologyNode `json:"nodes"`
	Edges           []ModuleRuntimeTopologyEdge `json:"edges"`
	ModuleNodes     []ModuleNodeItem            `json:"module_nodes"`
	DependencyEdges []ModuleEdgeItem            `json:"dependency_edges"`
}

type ModuleRuntimeTopologyNode struct {
	Id       string `json:"id"`
	ModuleId string `json:"module_id"`
	Label    string `json:"label"`
	Type     string `json:"type"`
	Status   string `json:"status"`
	Source   string `json:"source"`
	Config   any    `json:"config"`
}

type ModuleRuntimeTopologyEdge struct {
	Id       string `json:"id"`
	ModuleId string `json:"module_id"`
	From     string `json:"from"`
	To       string `json:"to"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
	Source   string `json:"source"`
}

type ModuleRuntimeRouteItem struct {
	RouteId       string   `json:"route_id"`
	ModuleId      string   `json:"module_id"`
	Prefix        string   `json:"prefix"`
	ServiceId     string   `json:"service_id"`
	TargetService string   `json:"target_service"`
	UpstreamBase  string   `json:"upstream_base,omitempty"`
	AuthMode      string   `json:"auth_mode"`
	Methods       []string `json:"methods"`
	Enabled       bool     `json:"enabled"`
	ProxyEnabled  bool     `json:"proxy_enabled"`
	Priority      int      `json:"priority"`
	StripPrefix   string   `json:"strip_prefix,omitempty"`
	RewritePrefix string   `json:"rewrite_prefix,omitempty"`
	HealthCheckId string   `json:"health_check_id,omitempty"`
	CreatedFrom   string   `json:"created_from"`
	Status        string   `json:"status"`
	ServiceState  string   `json:"service_state,omitempty"`
	ServiceHealth string   `json:"service_health,omitempty"`
	Conflicts     []string `json:"conflicts"`
	Warnings      []string `json:"warnings"`
	BlockedBy     []string `json:"blocked_by"`
}

type ModuleRuntimeRoutesResp struct {
	Version     string                   `json:"version"`
	GeneratedAt string                   `json:"generated_at"`
	Routes      []ModuleRuntimeRouteItem `json:"routes"`
	Warnings    []string                 `json:"warnings"`
	CanProxy    bool                     `json:"can_proxy"`
	Reloaded    bool                     `json:"reloaded,omitempty"`
}

type RuntimeServicesResp struct {
	Services []ModuleRuntimeService `json:"services"`
	Workers  []ModuleRuntimeService `json:"workers"`
}

type RuntimeServiceResp struct {
	Service ModuleRuntimeService `json:"service"`
}

type RuntimeServicePlanResp struct {
	Plan RuntimePlanItem `json:"plan"`
}

type RuntimePlanItem struct {
	PlanId       string               `json:"plan_id"`
	Action       string               `json:"action"`
	ServiceId    string               `json:"service_id"`
	ModuleId     string               `json:"module_id"`
	Driver       string               `json:"driver"`
	CanApply     bool                 `json:"can_apply"`
	ApplyEnabled bool                 `json:"apply_enabled"`
	Commands     []RuntimePlanCommand `json:"commands"`
	Affected     []string             `json:"affected"`
	BlockedBy    []string             `json:"blocked_by"`
	Warnings     []string             `json:"warnings"`
	CreatedAt    string               `json:"created_at"`
}

type RuntimePlanCommand struct {
	Tool string   `json:"tool"`
	Args []string `json:"args"`
}

type ModuleDetailResp struct {
	Module         ModuleNodeItem            `json:"module"`
	Dependencies   []ModuleEdgeItem          `json:"dependencies"`
	Dependents     []ModuleEdgeItem          `json:"dependents"`
	Components     []ModuleComponentItem     `json:"components"`
	Permissions    []ModulePermissionItem    `json:"permissions"`
	Menus          []ModuleMenuItem          `json:"menus"`
	FrontendRoutes []ModuleFrontendRouteItem `json:"frontend_routes"`
	GatewayRoutes  []ModuleGatewayRouteItem  `json:"gateway_routes"`
	Installations  []ModuleInstallationItem  `json:"installations"`
	HealthChecks   []ModuleComponentItem     `json:"health_checks"`
}

type ModuleInstallerReq struct {
	ManifestPath string `json:"manifest_path,optional"`
	Manifest     any    `json:"manifest,optional"`
	DryRun       bool   `json:"dry_run,optional"`
}

type ModuleInstallerResp struct {
	Code  int                   `json:"code"`
	Msg   string                `json:"msg"`
	Data  any                   `json:"data"`
	Error *ModuleInstallerError `json:"error,omitempty"`
}

type ModuleInstallerError struct {
	Code     string         `json:"code"`
	Message  string         `json:"message"`
	Severity string         `json:"severity"`
	Details  map[string]any `json:"details,omitempty"`
}
