services:
  postgres:
    image: postgres:17
    container_name: ojos-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ojos
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    container_name: ojos-redis
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ojos-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"

  gateway:
    build:
      context: ../../services
      dockerfile: gateway/Dockerfile
    container_name: ojos-gateway
    depends_on:
      postgres:
        condition: service_healthy
      problem-api:
        condition: service_started
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/ojos?sslmode=disable"
    ports:
      - "8080:8080"

  auth:
    build:
      context: ../../services
      dockerfile: auth/Dockerfile
    container_name: ojos-auth
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      jaeger:
        condition: service_started
    expose:
      - "8081"

  judge-api:
    build:
      context: ../../services
      dockerfile: judge-api/Dockerfile
    container_name: ojos-judge-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8082"
    volumes:
      - ../../storage/submissions:/data/ojos/submissions

  judge-worker:
    build:
      context: ../../services
      dockerfile: judge-worker/Dockerfile
    container_name: ojos-judge-worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/ojos?sslmode=disable
      REDIS_URL: redis://ojos-redis:6379/0
      LANGUAGES_CONFIG: config/languages.yaml
      RUST_LOG: info
    cap_add:
      - SYS_ADMIN
      - SYS_CHROOT
      - SETUID
      - SETGID
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    volumes:
      - ../../storage/problems:/data/ojos/problems:ro
      - ../../storage/submissions:/data/ojos/submissions
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  problem-api:
    build:
      context: ../../services
      dockerfile: problem-api/Dockerfile
    container_name: ojos-problem-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      jaeger:
        condition: service_started
    expose:
      - "8083"
    volumes:
      - ../../storage/problems:/data/ojos/problems

volumes:
  postgres-data: