[package]
name = "ojos-orchestrator-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
orchestrator-core.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq = { version = "3.3", default-features = false, features = ["rustls"] }
