// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-storage-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/buckets",
				Handler: listBucketsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/buckets/:bucket",
				Handler: ensureBucketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metadata/:bucket/:key",
				Handler: getMetadataHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/objects/:bucket/:key",
				Handler: putObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/objects/:bucket/:key",
				Handler: getObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodHead,
				Path:    "/objects/:bucket/:key",
				Handler: headObjectHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/objects/:bucket/:key",
				Handler: deleteObjectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/storage"),
	)
}
