// Code generated by goctl. Safe to edit for service-first routes.

package handler

import (
	"net/http"

	"ojos-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/health",
				Handler: adminHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/health",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services",
				Handler: adminServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/sets",
				Handler: adminServiceSetsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/sets",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/topology",
				Handler: adminServiceTopologyHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/topology",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/orchestrator/snapshot",
				Handler: adminOrchestratorSnapshotHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/orchestrator/snapshot",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/orchestrator/routes",
				Handler: adminOrchestratorRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/orchestrator/routes",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services/status",
				Handler: adminServiceStatusServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services/status",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services/status/operations",
				Handler: adminServiceStatusOperationsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services/status/operations",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services/status/operations/:id",
				Handler: adminServiceStatusOperationDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services/status/operations/:id",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services/status/:id",
				Handler: adminServiceStatusServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services/status/:id",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services/:id",
				Handler: adminServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services/:id",
				Handler: preflightHandler(),
			},
		},
	)
}
