// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/health",
				Handler: adminHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/health",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules",
				Handler: adminModulesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/discover",
				Handler: adminModuleInstallerDiscoverHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/discover",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/validate",
				Handler: adminModuleInstallerValidateHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/validate",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/plan",
				Handler: adminModuleInstallerPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/plan",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/install",
				Handler: adminModuleInstallerInstallHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/install",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/sets",
				Handler: adminModuleSetsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/sets",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/topology",
				Handler: adminModuleTopologyHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/topology",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/runtime-snapshot",
				Handler: adminModuleRuntimeSnapshotHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/runtime-snapshot",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/runtime/routes",
				Handler: adminModuleRuntimeRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/runtime/routes",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/runtime/reload",
				Handler: adminModuleRuntimeReloadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/services",
				Handler: adminRuntimeServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/operations",
				Handler: adminRuntimeOperationsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/operations",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/operations/:id",
				Handler: adminRuntimeOperationDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/operations/:id",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/plans/:id/apply",
				Handler: adminRuntimeApplyPlanDisabledHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/plans/:id/apply",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-start",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "start"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-start",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-stop",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "stop"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-stop",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-restart",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "restart"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-restart",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-reload",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "reload"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-reload",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/services/:id",
				Handler: adminRuntimeServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/reload",
				Handler: adminRuntimeReloadHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/reload",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/runtime/reload",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/:id/enable",
				Handler: adminModuleInstallerEnableHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/enable",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/:id/disable",
				Handler: adminModuleInstallerDisableHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/disable",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/:id/upgrade-plan",
				Handler: adminModuleInstallerUpgradePlanHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/upgrade-plan",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/:id/rollback-plan",
				Handler: adminModuleInstallerRollbackPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/rollback-plan",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/modules/:id/uninstall-dry-run",
				Handler: adminModuleInstallerUninstallDryRunHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/uninstall-dry-run",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/:id/health",
				Handler: adminModuleInstallerHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/health",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/:id/operations",
				Handler: adminModuleInstallerOperationsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id/operations",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/modules/:id",
				Handler: adminModuleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/modules/:id",
				Handler: preflightHandler(),
			},
		},
	)
}
