// Code generated by goctl. Safe to edit for service-first routes.

package handler

import (
	"net/http"

	"ojos-gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/health",
				Handler: adminHealthHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/health",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services",
				Handler: adminServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/sets",
				Handler: adminServiceSetsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/sets",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/topology",
				Handler: adminServiceTopologyHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/topology",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/snapshot",
				Handler: adminServiceRuntimeSnapshotHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/snapshot",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/routes",
				Handler: adminServiceRuntimeRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/routes",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/reload",
				Handler: adminRuntimeReloadHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/reload",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/services",
				Handler: adminRuntimeServicesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/services/:id",
				Handler: adminRuntimeServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-start",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "start"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-start",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-stop",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "stop"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-stop",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-restart",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "restart"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-restart",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/services/:id/plan-reload",
				Handler: adminRuntimeServicePlanHandler(serverCtx, "reload"),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/services/:id/plan-reload",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/operations",
				Handler: adminRuntimeOperationsHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/operations",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/runtime/operations/:id",
				Handler: adminRuntimeOperationDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/operations/:id",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/admin/runtime/plans/:id/apply",
				Handler: adminRuntimeApplyPlanDisabledHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/runtime/plans/:id/apply",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/devices",
				Handler: adminServiceDevicesHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/devices",
				Handler: preflightHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/admin/services/:id",
				Handler: adminServiceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodOptions,
				Path:    "/api/admin/services/:id",
				Handler: preflightHandler(),
			},
		},
	)
}
