// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddTestCaseReq struct {
	ProblemId     int64  `path:"id"`
	CaseNo        int    `json:"case_no,optional"`
	Input         string `json:"input"`
	Answer        string `json:"answer"`
	Score         int    `json:"score,optional"`
	Group         int    `json:"group,optional"`
	Sample        bool   `json:"sample,optional"`
	Hidden        bool   `json:"hidden,optional"`
	TimeLimitMs   int    `json:"time_limit_ms,optional"`
	MemoryLimitMb int    `json:"memory_limit_mb,optional"`
}

type AddTestCaseResp struct {
	CaseNo     int    `json:"case_no"`
	InputPath  string `json:"input_path"`
	AnswerPath string `json:"answer_path"`
}

type CreateProblemReq struct {
	Title         string `json:"title"`
	Slug          string `json:"slug,optional"`
	Statement     string `json:"statement,optional"`
	TimeLimitMs   int    `json:"time_limit_ms,optional"`
	MemoryLimitMb int    `json:"memory_limit_mb,optional"`
	ProblemType   string `json:"problem_type,optional"`
	Visibility    string `json:"visibility,optional"`
}

type CreateProblemResp struct {
	ProblemId  int64  `json:"problem_id"`
	Slug       string `json:"slug"`
	PackageDir string `json:"package_dir"`
}

type DeleteProblemReq struct {
	Id int64 `path:"id"`
}

type DeleteProblemResp struct {
	Deleted bool `json:"deleted"`
}

type DeleteTestCaseReq struct {
	ProblemId int64 `path:"id"`
	CaseNo    int   `path:"case_no"`
}

type DeleteTestCaseResp struct {
	Deleted bool `json:"deleted"`
}

type GetProblemReq struct {
	Id int64 `path:"id"`
}

type GetProblemResp struct {
	Problem ProblemItem `json:"problem"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type ListProblemsReq struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"page_size,optional"`
}

type ListProblemsResp struct {
	Problems []ProblemItem `json:"problems"`
	Total    int64         `json:"total"`
}

type ListTestCasesReq struct {
	ProblemId int64 `path:"id"`
}

type ListTestCasesResp struct {
	Cases []TestCaseItem `json:"cases"`
}

type ProblemItem struct {
	Id             int64  `json:"id"`
	Slug           string `json:"slug"`
	Title          string `json:"title"`
	Statement      string `json:"statement"`
	ProblemType    string `json:"problem_type"`
	Visibility     string `json:"visibility"`
	PackageDir     string `json:"package_dir"`
	ManifestPath   string `json:"manifest_path"`
	ManifestSha256 string `json:"manifest_sha256"`
	SourceFormat   string `json:"source_format"`
	Status         string `json:"status"`
	TimeLimitMs    int    `json:"time_limit_ms"`
	MemoryLimitMb  int    `json:"memory_limit_mb"`
	CreatedBy      int64  `json:"created_by"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type TestCaseItem struct {
	No            int    `json:"no"`
	Input         string `json:"input"`
	Answer        string `json:"answer"`
	Score         int    `json:"score"`
	Group         int    `json:"group"`
	Sample        bool   `json:"sample"`
	Hidden        bool   `json:"hidden"`
	TimeLimitMs   int    `json:"time_limit_ms"`
	MemoryLimitMb int    `json:"memory_limit_mb"`
}

type UpdateProblemReq struct {
	Id            int64  `path:"id"`
	Title         string `json:"title,optional"`
	Statement     string `json:"statement,optional"`
	TimeLimitMs   int    `json:"time_limit_ms,optional"`
	MemoryLimitMb int    `json:"memory_limit_mb,optional"`
	ProblemType   string `json:"problem_type,optional"`
	Visibility    string `json:"visibility,optional"`
	Status        string `json:"status,optional"`
}

type UpdateTestCaseReq struct {
	ProblemId     int64  `path:"id"`
	CaseNo        int    `path:"case_no"`
	Input         string `json:"input"`
	Answer        string `json:"answer"`
	Score         int    `json:"score,optional"`
	Group         int    `json:"group,optional"`
	Sample        bool   `json:"sample,optional"`
	Hidden        bool   `json:"hidden,optional"`
	TimeLimitMs   int    `json:"time_limit_ms,optional"`
	MemoryLimitMb int    `json:"memory_limit_mb,optional"`
}

type UpdateTestCaseResp struct {
	CaseNo     int    `json:"case_no"`
	InputPath  string `json:"input_path"`
	AnswerPath string `json:"answer_path"`
}
