use super::*;

pub(super) fn render_go_mod(contract: &ServiceContractV3) -> String {
    format!(
        "module ojos.local/gen/{}\n\ngo 1.23\n",
        go_package(&contract.service_id)
    )
}

pub(super) fn render_go_client(contract: &ServiceContractV3) -> String {
    let package = go_package(&contract.service_id);
    let mut source = format!(
        r#"// Code generated by ojos service. DO NOT EDIT.
package {package}

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"
)

type ContextSnapshot struct {{
	Generation uint64
	BaseURL string
	Token string
}}

type ContextSnapshotProvider interface {{
	Current(context.Context) (ContextSnapshot, error)
}}

type ContextSnapshotProviderFunc func(context.Context) (ContextSnapshot, error)

func (provider ContextSnapshotProviderFunc) Current(ctx context.Context) (ContextSnapshot, error) {{
	return provider(ctx)
}}

type StaticContextProvider struct {{ Snapshot ContextSnapshot }}

func (provider StaticContextProvider) Current(context.Context) (ContextSnapshot, error) {{
	return provider.Snapshot, nil
}}

type Client struct {{
	Context ContextSnapshotProvider
	HTTPClient *http.Client
	Timeout time.Duration
}}

type Operation struct {{
	ID string
	Method string
	Path string
	Audience string
	Permission string
	HeaderParameters []HeaderParameter
	RequestContentTypes []string
	RequestBodyRequired bool
}}

type HeaderParameter struct {{
	Name string
	Required bool
}}

type CallOptions struct {{
	IdempotencyKey string
	Timeout time.Duration
	Headers http.Header
	ContentType string
	RawBody []byte
}}

type ErrorKind string

const (
	ErrorConfiguration ErrorKind = "configuration"
	ErrorTimeout ErrorKind = "timeout"
	ErrorTransport ErrorKind = "transport"
	ErrorUnauthorized ErrorKind = "unauthorized"
	ErrorForbidden ErrorKind = "forbidden"
	ErrorNotFound ErrorKind = "not_found"
	ErrorConflict ErrorKind = "conflict"
	ErrorRateLimited ErrorKind = "rate_limited"
	ErrorServer ErrorKind = "server"
)

type ClientError struct {{
	Kind ErrorKind
	StatusCode int
	Err error
}}

func (err *ClientError) Error() string {{
	if err.Err != nil {{ return fmt.Sprintf("%s: %v", err.Kind, err.Err) }}
	return fmt.Sprintf("%s (status %d)", err.Kind, err.StatusCode)
}}

func (err *ClientError) Unwrap() error {{ return err.Err }}

var Operations = map[string]Operation{{
"#
    );
    for operation in sorted_operations(contract) {
        source.push_str(&format!(
            "\t{}: {{ID: {}, Method: {}, Path: {}, Audience: {}, Permission: {}, HeaderParameters: {}, RequestContentTypes: {}, RequestBodyRequired: {}}},\n",
            go_string(&operation.operation_id),
            go_string(&operation.operation_id),
            go_string(&operation.method),
            go_string(&operation.provider_path),
            go_string(&operation.audience),
            go_string(operation.permission.as_deref().unwrap_or("")),
            go_header_parameters(operation),
            go_request_content_types(operation),
            operation
                .request_body
                .as_ref()
                .map(|body| body.required)
                .unwrap_or(false),
        ));
    }
    source.push_str(
        r#"}

func NewClient(provider ContextSnapshotProvider, httpClient *http.Client) *Client {
	if httpClient == nil { httpClient = http.DefaultClient }
	return &Client{Context: provider, HTTPClient: httpClient, Timeout: 30 * time.Second}
}

func expandPath(template string, parameters map[string]string) (string, error) {
	path := template
	for key, value := range parameters { path = strings.ReplaceAll(path, "{"+key+"}", url.PathEscape(value)) }
	if strings.Contains(path, "{") { return "", fmt.Errorf("missing path parameter for %s", template) }
	return path, nil
}

func (c *Client) Do(ctx context.Context, operation Operation, pathParameters map[string]string, query url.Values, body []byte) (*http.Response, error) {
	return c.DoWithOptions(ctx, operation, pathParameters, query, body, CallOptions{})
}

func (c *Client) DoWithOptions(ctx context.Context, operation Operation, pathParameters map[string]string, query url.Values, body []byte, options CallOptions) (*http.Response, error) {
	if c == nil || c.Context == nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: errors.New("context snapshot provider is required")} }
	snapshot, err := c.Context.Current(ctx)
	if err != nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: err} }
	baseURL := strings.TrimRight(strings.TrimSpace(snapshot.BaseURL), "/")
	if baseURL == "" { return nil, &ClientError{Kind: ErrorConfiguration, Err: errors.New("context snapshot base URL is required")} }
	path, err := expandPath(operation.Path, pathParameters)
	if err != nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: err} }
	target, err := url.Parse(baseURL + path)
	if err != nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: err} }
	target.RawQuery = query.Encode()
	timeout := options.Timeout
	if timeout <= 0 { timeout = c.Timeout }
	effectiveBody := body
	if options.RawBody != nil {
		if body != nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: errors.New("body and raw body cannot both be set")} }
		effectiveBody = options.RawBody
	}
	if operation.RequestBodyRequired && effectiveBody == nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: errors.New("request body is required")} }
	contentType, err := selectContentType(operation, options.ContentType, effectiveBody != nil)
	if err != nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: err} }
	requestContext := ctx
	var cancel context.CancelFunc
	if timeout > 0 { requestContext, cancel = context.WithTimeout(ctx, timeout); defer cancel() }
	request, err := http.NewRequestWithContext(requestContext, operation.Method, target.String(), bytes.NewReader(effectiveBody))
	if err != nil { return nil, &ClientError{Kind: ErrorConfiguration, Err: err} }
	for name, values := range options.Headers {
		if !validHeaderName(name) { return nil, &ClientError{Kind: ErrorConfiguration, Err: fmt.Errorf("invalid header name %q", name)} }
		if forbiddenHeader(name) { return nil, &ClientError{Kind: ErrorConfiguration, Err: fmt.Errorf("header %s cannot be overridden", name)} }
		for _, value := range values {
			if !validHeaderValue(value) { return nil, &ClientError{Kind: ErrorConfiguration, Err: fmt.Errorf("invalid value for header %s", name)} }
			request.Header.Add(name, value)
		}
	}
	if contentType != "" { request.Header.Set("Content-Type", contentType) }
	if snapshot.Token != "" { request.Header.Set("Authorization", "Bearer "+snapshot.Token) }
	if key := strings.TrimSpace(options.IdempotencyKey); key != "" { request.Header.Set("Idempotency-Key", key) }
	for _, parameter := range operation.HeaderParameters {
		if parameter.Required && strings.TrimSpace(request.Header.Get(parameter.Name)) == "" { return nil, &ClientError{Kind: ErrorConfiguration, Err: fmt.Errorf("required header %s is missing", parameter.Name)} }
	}
	response, err := c.HTTPClient.Do(request)
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) || errors.Is(requestContext.Err(), context.DeadlineExceeded) { return nil, &ClientError{Kind: ErrorTimeout, Err: err} }
		return nil, &ClientError{Kind: ErrorTransport, Err: err}
	}
	if kind := statusErrorKind(response.StatusCode); kind != "" { return response, &ClientError{Kind: kind, StatusCode: response.StatusCode} }
	return response, nil
}

func selectContentType(operation Operation, requested string, hasBody bool) (string, error) {
	requested = strings.TrimSpace(requested)
	if !hasBody {
		if requested != "" { return "", errors.New("content type cannot be set without a request body") }
		return "", nil
	}
	if requested == "" && len(operation.RequestContentTypes) != 0 { return operation.RequestContentTypes[0], nil }
	if requested == "" { return "", nil }
	for _, declared := range operation.RequestContentTypes { if strings.EqualFold(requested, declared) { return declared, nil } }
	return "", fmt.Errorf("content type %s is not declared for operation %s", requested, operation.ID)
}

func forbiddenHeader(name string) bool {
	name = strings.ToLower(strings.TrimSpace(name))
	if strings.HasPrefix(name, "proxy-") || strings.HasPrefix(name, "sec-") || strings.HasPrefix(name, "x-forwarded-") || strings.HasPrefix(name, "x-ojos-caller-") || strings.HasPrefix(name, "x-ojos-gateway-") || strings.HasPrefix(name, "x-ojos-internal-") || strings.HasPrefix(name, "x-ojos-workload-") { return true }
	switch name {
	case "authorization", "host", "cookie", "set-cookie", "connection", "keep-alive", "te", "trailer", "transfer-encoding", "upgrade", "content-length", "content-type", "idempotency-key", "forwarded", "via", "expect", "x-api-key", "api-key":
		return true
	default:
		return false
	}
}

func validHeaderName(name string) bool {
	if name == "" { return false }
	for _, character := range name {
		if (character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') || strings.ContainsRune("!#$%&'*+-.^_`|~", character) { continue }
		return false
	}
	return true
}

func validHeaderValue(value string) bool {
	for _, character := range value { if character == '\r' || character == '\n' || character == 0x7f || (character < 0x20 && character != '\t') { return false } }
	return true
}

func statusErrorKind(status int) ErrorKind {
	switch status {
	case http.StatusUnauthorized: return ErrorUnauthorized
	case http.StatusForbidden: return ErrorForbidden
	case http.StatusNotFound: return ErrorNotFound
	case http.StatusConflict: return ErrorConflict
	case http.StatusTooManyRequests: return ErrorRateLimited
	default:
		if status >= 500 { return ErrorServer }
		return ""
	}
}
"#,
    );
    for operation in sorted_operations(contract) {
        let name = go_exported(&operation.operation_id);
        source.push_str(&format!(
            "\nfunc (c *Client) {name}(ctx context.Context, pathParameters map[string]string, query url.Values, body []byte) (*http.Response, error) {{\n\treturn c.Do(ctx, Operations[{}], pathParameters, query, body)\n}}\n\nfunc (c *Client) {name}WithOptions(ctx context.Context, pathParameters map[string]string, query url.Values, body []byte, options CallOptions) (*http.Response, error) {{\n\treturn c.DoWithOptions(ctx, Operations[{}], pathParameters, query, body, options)\n}}\n",
            go_string(&operation.operation_id),
            go_string(&operation.operation_id)
        ));
    }
    source
}

pub(super) fn render_go_events(contract: &ServiceContractV3) -> Result<String> {
    let package = go_package(&contract.service_id);
    let events = all_events(contract);
    let mut source =
        format!("// Code generated by ojos service. DO NOT EDIT.\npackage {package}\n");
    if !events.is_empty() {
        source.push_str(
            "\nimport (\n\t\"bytes\"\n\t\"encoding/json\"\n\t\"errors\"\n\t\"fmt\"\n\t\"io\"\n\t\"strconv\"\n)\n",
        );
    }
    source.push_str(
        r#"
type EventDescriptor[T any] struct {
	Type string `json:"type"`
	Version uint32 `json:"version"`
	SchemaDigest string `json:"schemaDigest"`
	Delivery string `json:"delivery"`
}

type TypedEvent[T any] struct {
	Descriptor EventDescriptor[T] `json:"descriptor"`
	Payload T `json:"payload"`
}

func (descriptor EventDescriptor[T]) New(payload T) TypedEvent[T] {
	return TypedEvent[T]{Descriptor: descriptor, Payload: payload}
}

"#,
    );
    if !events.is_empty() {
        source.push_str(
            r#"func strictEventJSON(data []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil { return err }
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil { return errors.New("multiple JSON values") }
		return err
	}
	return nil
}

func mustEventSchema(document string) map[string]any {
	var schema map[string]any
	if err := strictEventJSON([]byte(document), &schema); err != nil { panic(err) }
	return schema
}

func validateEventValue(value any, schema map[string]any, path string) error {
	if constant, ok := schema["const"]; ok {
		if value != constant { return fmt.Errorf("%s must equal %v", path, constant) }
		return nil
	}
	if values, ok := schema["enum"].([]any); ok {
		for _, candidate := range values { if value == candidate { return nil } }
		return fmt.Errorf("%s is not an allowed value", path)
	}
	kind, _ := schema["type"].(string)
	switch kind {
	case "object":
		object, ok := value.(map[string]any); if !ok { return fmt.Errorf("%s must be an object", path) }
		properties, ok := schema["properties"].(map[string]any); if !ok { return fmt.Errorf("%s has an invalid schema", path) }
		for key := range object { if _, ok := properties[key]; !ok { return fmt.Errorf("%s contains unknown field %q", path, key) } }
		if required, ok := schema["required"].([]any); ok {
			for _, item := range required {
				name, ok := item.(string); if !ok { return fmt.Errorf("%s has an invalid schema", path) }
				if _, present := object[name]; !present { return fmt.Errorf("%s is missing required field %q", path, name) }
			}
		}
		for key, rawSchema := range properties {
			child, present := object[key]; if !present { continue }
			childSchema, ok := rawSchema.(map[string]any); if !ok { return fmt.Errorf("%s.%s has an invalid schema", path, key) }
			if err := validateEventValue(child, childSchema, path+"."+key); err != nil { return err }
		}
		return nil
	case "array":
		array, ok := value.([]any); if !ok { return fmt.Errorf("%s must be an array", path) }
		itemSchema, ok := schema["items"].(map[string]any); if !ok { return fmt.Errorf("%s has an invalid schema", path) }
		for index, item := range array { if err := validateEventValue(item, itemSchema, fmt.Sprintf("%s[%d]", path, index)); err != nil { return err } }
		return nil
	case "string":
		if _, ok := value.(string); !ok { return fmt.Errorf("%s must be a string", path) }
	case "integer":
		number, ok := value.(json.Number); if !ok { return fmt.Errorf("%s must be an integer", path) }
		if _, err := strconv.ParseInt(number.String(), 10, 64); err != nil { return fmt.Errorf("%s must be a signed 64-bit integer", path) }
	case "number":
		number, ok := value.(json.Number); if !ok { return fmt.Errorf("%s must be a number", path) }
		if _, err := strconv.ParseFloat(number.String(), 64); err != nil { return fmt.Errorf("%s must be a finite number", path) }
	case "boolean":
		if _, ok := value.(bool); !ok { return fmt.Errorf("%s must be a boolean", path) }
	default:
		return fmt.Errorf("%s has unsupported schema type %q", path, kind)
	}
	return nil
}

func validateEventPayloadJSON(data []byte, schema map[string]any) error {
	var value any
	if err := strictEventJSON(data, &value); err != nil { return err }
	return validateEventValue(value, schema, "payload")
}

"#,
        );
    }
    source.push('\n');
    for event in events {
        let name = go_exported(&format!("{}V{}", event.event_type, event.version));
        source.push_str(&render_go_payload(&name, &event.payload_schema)?);
        let schema_json = serde_json_canonicalizer::to_vec(&event.payload_schema)
            .map_err(CodegenError::Serialize)?;
        let schema_json = String::from_utf8(schema_json)
            .map_err(|error| CodegenError::Drift(error.to_string()))?;
        source.push_str(&format!(
            "const {name}Type = {}\nconst {name}Version uint32 = {}\nconst {name}SchemaDigest = {}\nconst {name}Delivery = {}\n\nvar {name}Descriptor = EventDescriptor[{name}Payload]{{Type: {name}Type, Version: {name}Version, SchemaDigest: {name}SchemaDigest, Delivery: {name}Delivery}}\nvar {}PayloadSchema = mustEventSchema({})\n\nfunc Encode{name}(value TypedEvent[{name}Payload]) ([]byte, error) {{\n\tif value.Descriptor.Type != {name}Type || value.Descriptor.Version != {name}Version || value.Descriptor.SchemaDigest != {name}SchemaDigest || value.Descriptor.Delivery != {name}Delivery {{ return nil, errors.New(\"event descriptor mismatch\") }}\n\tpayload, err := json.Marshal(value.Payload); if err != nil {{ return nil, err }}\n\tif err := validateEventPayloadJSON(payload, {}PayloadSchema); err != nil {{ return nil, err }}\n\treturn json.Marshal(value)\n}}\nfunc Decode{name}(data []byte) (TypedEvent[{name}Payload], error) {{\n\tvar result TypedEvent[{name}Payload]\n\tvar wire struct {{ Descriptor EventDescriptor[{name}Payload] `json:\"descriptor\"`; Payload json.RawMessage `json:\"payload\"` }}\n\tif err := strictEventJSON(data, &wire); err != nil {{ return result, err }}\n\tif wire.Descriptor.Type != {name}Type || wire.Descriptor.Version != {name}Version || wire.Descriptor.SchemaDigest != {name}SchemaDigest || wire.Descriptor.Delivery != {name}Delivery {{ return result, errors.New(\"event descriptor mismatch\") }}\n\tif err := validateEventPayloadJSON(wire.Payload, {}PayloadSchema); err != nil {{ return result, err }}\n\tvar payload {name}Payload; if err := strictEventJSON(wire.Payload, &payload); err != nil {{ return result, err }}\n\treturn TypedEvent[{name}Payload]{{Descriptor: {name}Descriptor, Payload: payload}}, nil\n}}\n\n",
            go_string(&event.event_type),
            event.version,
            go_string(&event.schema.digest),
            go_string(&event.delivery),
            go_unexported(&name),
            go_string(&schema_json),
            go_unexported(&name),
            go_unexported(&name),
        ));
    }
    while source.ends_with("\n\n") {
        source.pop();
    }
    Ok(source)
}

pub(super) fn render_go_payload(event_name: &str, schema: &Value) -> Result<String> {
    let mut declarations = String::new();
    let mut names = BTreeSet::new();
    render_go_object(
        &format!("{event_name}Payload"),
        schema,
        &mut declarations,
        &mut names,
    )?;
    Ok(declarations)
}

pub(super) fn render_go_object(
    name: &str,
    schema: &Value,
    output: &mut String,
    names: &mut BTreeSet<String>,
) -> Result<()> {
    insert_identifier(names, name.to_string(), "Go event payload")?;
    let (properties, required) = schema_properties(schema)?;
    let mut nested = String::new();
    let mut fields = BTreeSet::new();
    output.push_str(&format!("type {name} struct {{\n"));
    for (property, property_schema) in properties {
        let field = go_exported(property);
        insert_identifier(&mut fields, field.clone(), "Go event field")?;
        let nested_name = format!("{name}{field}");
        let mut field_type = go_schema_type(&nested_name, property_schema, &mut nested, names)?;
        let is_required = required.contains(property.as_str());
        if !is_required {
            field_type = format!("*{field_type}");
        }
        output.push_str(&format!(
            "\t{field} {field_type} `json:\"{property}{}\"`\n",
            if is_required { "" } else { ",omitempty" }
        ));
    }
    output.push_str("}\n\n");
    output.push_str(&nested);
    Ok(())
}

pub(super) fn go_schema_type(
    name: &str,
    schema: &Value,
    nested: &mut String,
    names: &mut BTreeSet<String>,
) -> Result<String> {
    Ok(match schema_kind(schema)? {
        "object" => {
            render_go_object(name, schema, nested, names)?;
            name.to_string()
        }
        "array" => {
            let items = schema_object(schema)?
                .get("items")
                .ok_or_else(|| CodegenError::Drift("event array needs items".to_string()))?;
            format!(
                "[]{}",
                go_schema_type(&format!("{name}Item"), items, nested, names)?
            )
        }
        "string"
            if schema_object(schema)?.contains_key("enum")
                || schema_object(schema)?.contains_key("const") =>
        {
            insert_identifier(names, name.to_string(), "Go event payload")?;
            let values = schema_string_values(schema)?;
            let mut constants = BTreeSet::new();
            nested.push_str(&format!("type {name} string\n\nconst (\n"));
            for value in values {
                let constant = format!("{name}Value{}", go_exported(value));
                insert_identifier(&mut constants, constant.clone(), "Go event enum value")?;
                nested.push_str(&format!("\t{constant} {name} = {}\n", go_string(value)));
            }
            nested.push_str(")\n\n");
            name.to_string()
        }
        "string" => "string".to_string(),
        "integer" => "int64".to_string(),
        "number" => "float64".to_string(),
        "boolean" => "bool".to_string(),
        kind => {
            return Err(CodegenError::Drift(format!(
                "unsupported event type {kind}"
            )));
        }
    })
}

pub(super) fn render_gozero_api(contract: &ServiceContractV3) -> String {
    let mut source = format!(
        "// Code generated by ojos service. DO NOT EDIT.\nsyntax = \"v1\"\n\ninfo (\n\ttitle: {}\n\tdesc: {}\n\tversion: {}\n)\n\n",
        gozero_string(&contract.display_name),
        gozero_string(&format!("Generated adapter for {}", contract.service_id)),
        gozero_string(&contract.service_version.to_string()),
    );
    for operation in sorted_operations(contract) {
        let type_name = go_exported(&operation.operation_id);
        let mut fields = Vec::new();
        for parameter in &operation.parameters {
            fields.push(format!(
                "\t{} string `{tag}:\"{}{}\"`",
                go_exported(&parameter.name),
                parameter.name,
                if parameter.required { "" } else { ",optional" },
                tag = match parameter.location.as_str() {
                    "path" => "path",
                    "header" => "header",
                    _ => "form",
                },
            ));
        }
        if operation.request_body.is_some() {
            fields.push("\tBody string `json:\"body,optional\"`".to_string());
        }
        if !fields.is_empty() {
            source.push_str(&format!(
                "type {type_name}Request {{\n{}\n}}\n\n",
                fields.join("\n")
            ));
        }
        source.push_str(&format!(
            "type {type_name}Response {{\n\tBody string `json:\"body,optional\"`\n}}\n\n"
        ));
    }
    source.push_str(&format!(
        "@server (\n\tgroup: {}\n)\nservice {}-api {{\n",
        go_package(&contract.service_id),
        go_package(&contract.service_id)
    ));
    for operation in sorted_operations(contract) {
        let name = go_exported(&operation.operation_id);
        let request = if operation.parameters.is_empty() && operation.request_body.is_none() {
            String::new()
        } else {
            format!(" ({name}Request)")
        };
        source.push_str(&format!(
            "\t@handler {name}\n\t{} {}{} returns ({name}Response)\n",
            operation.method.to_ascii_lowercase(),
            operation.provider_path,
            request,
        ));
    }
    source.push_str("}\n");
    source
}

pub(super) fn go_exported(value: &str) -> String {
    let mut output = String::new();
    for word in words(value) {
        let mut characters = word.chars();
        if let Some(first) = characters.next() {
            output.push(first.to_ascii_uppercase());
            output.extend(characters);
        }
    }
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "Generated");
    }
    output
}

pub(super) fn go_unexported(value: &str) -> String {
    let mut value = go_exported(value);
    if let Some(first) = value.get_mut(0..1) {
        first.make_ascii_lowercase();
    }
    value
}

pub(super) fn go_package(value: &str) -> String {
    let mut output = words(value)
        .into_iter()
        .map(|word| word.to_ascii_lowercase())
        .collect::<Vec<_>>()
        .join("_");
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "service_");
    }
    output
}

pub(super) fn go_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

pub(super) fn go_header_parameters(operation: &ApiOperationV3) -> String {
    let values = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "header")
        .map(|parameter| {
            format!(
                "{{Name: {}, Required: {}}}",
                go_string(&parameter.name),
                parameter.required
            )
        })
        .collect::<Vec<_>>();
    if values.is_empty() {
        "nil".to_string()
    } else {
        format!("[]HeaderParameter{{{}}}", values.join(", "))
    }
}

pub(super) fn go_request_content_types(operation: &ApiOperationV3) -> String {
    let Some(body) = &operation.request_body else {
        return "nil".to_string();
    };
    if body.content.is_empty() {
        return "nil".to_string();
    }
    format!(
        "[]string{{{}}}",
        body.content
            .iter()
            .map(|media| go_string(&media.media_type))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

pub(super) fn gozero_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}
