use super::*;

pub(super) fn render_rust_manifest(contract: &ServiceContractV3) -> String {
    format!(
        "[package]\nname = \"{}-client\"\nversion = \"{}\"\nedition = \"2021\"\npublish = false\n\n[lib]\npath = \"src/lib.rs\"\n\n[dependencies]\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\n\n[workspace]\n",
        rust_crate(&contract.service_id),
        contract.service_version
    )
}

pub(super) fn render_rust_lib(contract: &ServiceContractV3) -> String {
    format!(
        "// Code generated by ojos service. DO NOT EDIT.\npub mod client;\npub mod events;\n\npub const SERVICE_ID: &str = {};\npub const SERVICE_VERSION: &str = {};\n",
        rust_string(&contract.service_id),
        rust_string(&contract.service_version.to_string())
    )
}

pub(super) fn render_rust_client(contract: &ServiceContractV3) -> String {
    let mut source = r#"// Code generated by ojos service. DO NOT EDIT.
use std::{collections::BTreeMap, sync::Arc, time::Duration};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Operation {
    pub id: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub audience: &'static str,
    pub permission: Option<&'static str>,
    pub header_parameters: &'static [HeaderParameter],
    pub request_content_types: &'static [&'static str],
    pub request_body_required: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HeaderParameter { pub name: &'static str, pub required: bool }

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContextSnapshot {
    pub generation: u64,
    pub base_url: String,
    pub token: String,
}

pub trait ContextSnapshotProvider: Send + Sync {
    fn current(&self) -> Result<ContextSnapshot, ClientError>;
}

impl<F> ContextSnapshotProvider for F
where F: Fn() -> Result<ContextSnapshot, ClientError> + Send + Sync {
    fn current(&self) -> Result<ContextSnapshot, ClientError> { self() }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CallOptions {
    pub timeout: Duration,
    pub idempotency_key: Option<String>,
    pub headers: BTreeMap<String, String>,
    pub content_type: Option<String>,
    pub raw_body: Option<Vec<u8>>,
}

impl Default for CallOptions {
    fn default() -> Self { Self { timeout: Duration::from_secs(30), idempotency_key: None, headers: BTreeMap::new(), content_type: None, raw_body: None } }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorKind { Configuration, Timeout, Transport, Unauthorized, Forbidden, NotFound, Conflict, RateLimited, Server }

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientError {
    MissingPathParameter(String),
    InvalidContext(String),
    InvalidRequest(String),
    Http { kind: ErrorKind, status: Option<u16>, message: String },
}

"#.to_string();
    for operation in sorted_operations(contract) {
        source.push_str(&format!(
            "pub const {}: Operation = Operation {{ id: {}, method: {}, path: {}, audience: {}, permission: {}, header_parameters: {}, request_content_types: {}, request_body_required: {} }};\n",
            rust_const(&operation.operation_id),
            rust_string(&operation.operation_id),
            rust_string(&operation.method),
            rust_string(&operation.provider_path),
            rust_string(&operation.audience),
            rust_option(operation.permission.as_deref()),
            rust_header_parameters(operation),
            rust_request_content_types(operation),
            operation
                .request_body
                .as_ref()
                .map(|body| body.required)
                .unwrap_or(false),
        ));
    }
    source.push_str("\npub const OPERATIONS: &[Operation] = &[\n");
    for operation in sorted_operations(contract) {
        source.push_str(&format!("    {},\n", rust_const(&operation.operation_id)));
    }
    source.push_str(
        r#"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Request {
    pub method: &'static str,
    pub url: String,
    pub headers: BTreeMap<String, String>,
    pub body: Vec<u8>,
    pub timeout: Duration,
}

#[derive(Clone)]
pub struct Client { context: Arc<dyn ContextSnapshotProvider> }

impl Client {
    pub fn new(context: Arc<dyn ContextSnapshotProvider>) -> Self { Self { context } }

    pub fn request(&self, operation: Operation, path_parameters: &BTreeMap<String, String>, body: Vec<u8>) -> Result<Request, ClientError> {
        self.request_with_options(operation, path_parameters, body, CallOptions::default())
    }

    pub fn request_with_options(&self, operation: Operation, path_parameters: &BTreeMap<String, String>, body: Vec<u8>, options: CallOptions) -> Result<Request, ClientError> {
        let snapshot = self.context.current()?;
        let base_url = snapshot.base_url.trim_end_matches('/');
        if base_url.is_empty() { return Err(ClientError::InvalidContext("base URL is required".to_owned())); }
        let mut path = operation.path.to_owned();
        for (key, value) in path_parameters { path = path.replace(&format!("{{{key}}}"), &percent_encode(value)); }
        if let Some(start) = path.find('{') {
            let tail = &path[start + 1..];
            let key = tail.split('}').next().unwrap_or(tail);
            return Err(ClientError::MissingPathParameter(key.to_owned()));
        }
        let raw_body_present = options.raw_body.is_some();
        let effective_body = match options.raw_body {
            Some(_) if !body.is_empty() => return Err(ClientError::InvalidRequest("body and raw body cannot both be set".to_owned())),
            Some(raw_body) => raw_body,
            None => body,
        };
        let has_body = raw_body_present || !effective_body.is_empty();
        if operation.request_body_required && !has_body { return Err(ClientError::InvalidRequest("request body is required".to_owned())); }
        let content_type = select_content_type(operation, options.content_type.as_deref(), has_body)?;
        let mut headers = BTreeMap::new();
        for (name, value) in options.headers {
            if !valid_header_name(&name) { return Err(ClientError::InvalidRequest(format!("invalid header name {name:?}"))); }
            if forbidden_header(&name) { return Err(ClientError::InvalidRequest(format!("header {name} cannot be overridden"))); }
            if !valid_header_value(&value) { return Err(ClientError::InvalidRequest(format!("invalid value for header {name}"))); }
            headers.insert(name, value);
        }
        if let Some(content_type) = content_type { headers.insert("Content-Type".to_owned(), content_type); }
        if !snapshot.token.is_empty() { headers.insert("Authorization".to_owned(), format!("Bearer {}", snapshot.token)); }
        if let Some(key) = options.idempotency_key { if !key.trim().is_empty() { headers.insert("Idempotency-Key".to_owned(), key); } }
        for parameter in operation.header_parameters {
            if parameter.required && !headers.iter().any(|(name, value)| name.eq_ignore_ascii_case(parameter.name) && !value.trim().is_empty()) {
                return Err(ClientError::InvalidRequest(format!("required header {} is missing", parameter.name)));
            }
        }
        Ok(Request { method: operation.method, url: format!("{base_url}{path}"), headers, body: effective_body, timeout: options.timeout })
    }

    pub fn map_status(status: u16) -> Option<ClientError> {
        let kind = match status { 401 => ErrorKind::Unauthorized, 403 => ErrorKind::Forbidden, 404 => ErrorKind::NotFound, 409 => ErrorKind::Conflict, 429 => ErrorKind::RateLimited, 500..=599 => ErrorKind::Server, _ => return None };
        Some(ClientError::Http { kind, status: Some(status), message: format!("HTTP {status}") })
    }

    pub fn timeout_error(message: impl Into<String>) -> ClientError { ClientError::Http { kind: ErrorKind::Timeout, status: None, message: message.into() } }
}

fn select_content_type(operation: Operation, requested: Option<&str>, has_body: bool) -> Result<Option<String>, ClientError> {
    let requested = requested.map(str::trim).filter(|value| !value.is_empty());
    if !has_body {
        if requested.is_some() { return Err(ClientError::InvalidRequest("content type cannot be set without a request body".to_owned())); }
        return Ok(None);
    }
    if let Some(requested) = requested {
        if let Some(declared) = operation.request_content_types.iter().find(|declared| declared.eq_ignore_ascii_case(requested)) { return Ok(Some((*declared).to_owned())); }
        return Err(ClientError::InvalidRequest(format!("content type {requested} is not declared for operation {}", operation.id)));
    }
    Ok(operation.request_content_types.first().map(|value| (*value).to_owned()))
}

fn forbidden_header(name: &str) -> bool {
    let name = name.trim().to_ascii_lowercase();
    if ["proxy-", "sec-", "x-forwarded-", "x-ojos-caller-", "x-ojos-gateway-", "x-ojos-internal-", "x-ojos-workload-"].iter().any(|prefix| name.starts_with(prefix)) { return true; }
    matches!(name.as_str(), "authorization" | "host" | "cookie" | "set-cookie" | "connection" | "keep-alive" | "te" | "trailer" | "transfer-encoding" | "upgrade" | "content-length" | "content-type" | "idempotency-key" | "forwarded" | "via" | "expect" | "x-api-key" | "api-key")
}

fn valid_header_name(name: &str) -> bool {
    !name.is_empty() && name.bytes().all(|byte| byte.is_ascii_alphanumeric() || b"!#$%&'*+-.^_`|~".contains(&byte))
}

fn valid_header_value(value: &str) -> bool {
    value.bytes().all(|byte| byte == b'\t' || byte >= 0x20 && byte != 0x7f)
}

fn percent_encode(value: &str) -> String {
    let mut output = String::new();
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'.' | b'_' | b'~') { output.push(byte as char); }
        else { output.push_str(&format!("%{byte:02X}")); }
    }
    output
}

"#,
    );
    source.trim_end().to_owned() + "\n"
}

pub(super) fn render_rust_events(contract: &ServiceContractV3) -> Result<String> {
    let events = all_events(contract);
    let mut declarations = String::new();
    for event in &events {
        let type_name = rust_type(&format!("{}V{}", event.event_type, event.version));
        declarations.push_str(&render_rust_payload(&type_name, &event.payload_schema)?);
        let name = rust_const(&format!("{}V{}", event.event_type, event.version));
        declarations.push_str(&format!(
            "pub const {name}: EventDescriptor<{type_name}Payload> = EventDescriptor::new(EventIdentity {{ event_type: {}, version: {}, schema_digest: {}, delivery: {} }});\n\n",
            rust_string(&event.event_type),
            event.version,
            rust_string(&event.schema.digest),
            rust_string(&event.delivery),
        ));
    }
    let uses_optional_non_null = declarations.contains("deserialize_optional_non_null");

    let mut source = "// Code generated by ojos service. DO NOT EDIT.\n".to_string();
    if uses_optional_non_null {
        source
            .push_str("use serde::{de::DeserializeOwned, Deserialize, Deserializer, Serialize};\n");
    } else {
        source.push_str("use serde::{de::DeserializeOwned, Deserialize, Serialize};\n");
    }
    source.push_str("use std::marker::PhantomData;\n\n");
    if uses_optional_non_null {
        source.push_str(
            r#"fn deserialize_optional_non_null<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    T::deserialize(deserializer).map(Some)
}

"#,
        );
    }
    source.push_str(r#"#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EventIdentity {
    pub event_type: &'static str,
    pub version: u32,
    pub schema_digest: &'static str,
    pub delivery: &'static str,
}

#[derive(Debug, PartialEq, Eq)]
pub struct EventDescriptor<T> { pub identity: EventIdentity, marker: PhantomData<fn() -> T> }

impl<T> Copy for EventDescriptor<T> {}
impl<T> Clone for EventDescriptor<T> { fn clone(&self) -> Self { *self } }

impl<T> EventDescriptor<T> {
    pub const fn new(identity: EventIdentity) -> Self { Self { identity, marker: PhantomData } }
    pub fn bind(&self, payload: T) -> TypedEvent<T> { TypedEvent { descriptor: self.identity, payload } }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypedEvent<T> { pub descriptor: EventIdentity, pub payload: T }

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct WireIdentity {
    #[serde(rename = "type")]
    event_type: String,
    version: u32,
    #[serde(rename = "schemaDigest")]
    schema_digest: String,
    delivery: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct WireEvent<T> { descriptor: WireIdentity, payload: T }

impl EventIdentity {
    fn to_wire(self) -> WireIdentity {
        WireIdentity { event_type: self.event_type.to_owned(), version: self.version, schema_digest: self.schema_digest.to_owned(), delivery: self.delivery.to_owned() }
    }

    fn matches_wire(self, wire: &WireIdentity) -> bool {
        wire.event_type == self.event_type && wire.version == self.version && wire.schema_digest == self.schema_digest && wire.delivery == self.delivery
    }
}

impl<T: Serialize + DeserializeOwned> EventDescriptor<T> {
    pub fn encode(&self, payload: T) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(&WireEvent { descriptor: self.identity.to_wire(), payload })
    }

    pub fn decode(&self, json: &[u8]) -> Result<TypedEvent<T>, String> {
        let event: WireEvent<T> = serde_json::from_slice(json).map_err(|error| error.to_string())?;
        if !self.identity.matches_wire(&event.descriptor) { return Err("event descriptor mismatch".to_owned()); }
        Ok(TypedEvent { descriptor: self.identity, payload: event.payload })
    }
}

"#);
    source.push_str(&declarations);
    source.push_str("\npub const EVENTS: &[EventIdentity] = &[\n");
    for event in &events {
        source.push_str(&format!(
            "    {}.identity,\n",
            rust_const(&format!("{}V{}", event.event_type, event.version))
        ));
    }
    source.push_str("];\n");

    Ok(source)
}

pub(super) fn render_rust_payload(event_name: &str, schema: &Value) -> Result<String> {
    let mut declarations = String::new();
    let mut names = BTreeSet::new();
    render_rust_object(
        &format!("{event_name}Payload"),
        schema,
        &mut declarations,
        &mut names,
    )?;
    Ok(declarations)
}

pub(super) fn render_rust_object(
    name: &str,
    schema: &Value,
    output: &mut String,
    names: &mut BTreeSet<String>,
) -> Result<()> {
    insert_identifier(names, name.to_string(), "Rust event payload")?;
    let (properties, required) = schema_properties(schema)?;
    let mut nested = String::new();
    let mut fields = BTreeSet::new();
    output.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(deny_unknown_fields)]\npub struct {name} {{\n"
    ));
    for (property, property_schema) in properties {
        let field = rust_field(property);
        insert_identifier(&mut fields, field.clone(), "Rust event field")?;
        let nested_name = format!("{name}{}", rust_type(property));
        let mut field_type = rust_schema_type(&nested_name, property_schema, &mut nested, names)?;
        let is_required = required.contains(property.as_str());
        if !is_required {
            field_type = format!("Option<{field_type}>");
            output.push_str(&format!(
                "    #[serde(rename = {}, default, skip_serializing_if = \"Option::is_none\", deserialize_with = \"deserialize_optional_non_null\")]\n",
                rust_string(property)
            ));
        } else {
            output.push_str(&format!(
                "    #[serde(rename = {})]\n",
                rust_string(property)
            ));
        }
        output.push_str(&format!("    pub {field}: {field_type},\n"));
    }
    output.push_str("}\n\n");
    output.push_str(&nested);
    Ok(())
}

pub(super) fn rust_schema_type(
    name: &str,
    schema: &Value,
    nested: &mut String,
    names: &mut BTreeSet<String>,
) -> Result<String> {
    Ok(match schema_kind(schema)? {
        "object" => {
            render_rust_object(name, schema, nested, names)?;
            name.to_string()
        }
        "array" => {
            let items = schema_object(schema)?
                .get("items")
                .ok_or_else(|| CodegenError::Drift("event array needs items".to_string()))?;
            format!(
                "Vec<{}>",
                rust_schema_type(&format!("{name}Item"), items, nested, names)?
            )
        }
        "string"
            if schema_object(schema)?.contains_key("enum")
                || schema_object(schema)?.contains_key("const") =>
        {
            insert_identifier(names, name.to_string(), "Rust event payload")?;
            let mut variants = BTreeSet::new();
            nested.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\npub enum {name} {{\n"
            ));
            for value in schema_string_values(schema)? {
                let variant = format!("Value{}", rust_type(value));
                insert_identifier(&mut variants, variant.clone(), "Rust event enum value")?;
                nested.push_str(&format!(
                    "    #[serde(rename = {})]\n    {variant},\n",
                    rust_string(value)
                ));
            }
            nested.push_str("}\n\n");
            name.to_string()
        }
        "string" => "String".to_string(),
        "integer" => "i64".to_string(),
        "number" => "f64".to_string(),
        "boolean" => "bool".to_string(),
        kind => {
            return Err(CodegenError::Drift(format!(
                "unsupported event type {kind}"
            )));
        }
    })
}

pub(super) fn rust_const(value: &str) -> String {
    let mut output = words(value)
        .into_iter()
        .map(|word| word.to_ascii_uppercase())
        .collect::<Vec<_>>()
        .join("_");
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "GENERATED_");
    }
    output
}

pub(super) fn rust_type(value: &str) -> String {
    let mut output = go_exported(value);
    if is_rust_keyword(&output.to_ascii_lowercase()) {
        output.insert_str(0, "Generated");
    }
    output
}

pub(super) fn rust_field(value: &str) -> String {
    let words = words(value);
    let mut output = words
        .first()
        .cloned()
        .unwrap_or_else(|| "generated".to_string())
        .to_ascii_lowercase();
    for word in words.iter().skip(1) {
        output.push('_');
        output.push_str(&word.to_ascii_lowercase());
    }
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "field_");
    }
    if is_rust_keyword(&output) {
        output.insert_str(0, "field_");
    }
    output
}

pub(super) fn is_rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

pub(super) fn rust_crate(value: &str) -> String {
    let mut output = words(value)
        .into_iter()
        .map(|word| word.to_ascii_lowercase())
        .collect::<Vec<_>>()
        .join("-");
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert_str(0, "service-");
    }
    output
}

pub(super) fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

pub(super) fn rust_option(value: Option<&str>) -> String {
    value
        .map(|value| format!("Some({})", rust_string(value)))
        .unwrap_or_else(|| "None".to_string())
}

pub(super) fn rust_header_parameters(operation: &ApiOperationV3) -> String {
    let values = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "header")
        .map(|parameter| {
            format!(
                "HeaderParameter {{ name: {}, required: {} }}",
                rust_string(&parameter.name),
                parameter.required
            )
        })
        .collect::<Vec<_>>();
    format!("&[{}]", values.join(", "))
}

pub(super) fn rust_request_content_types(operation: &ApiOperationV3) -> String {
    let values = operation
        .request_body
        .iter()
        .flat_map(|body| &body.content)
        .map(|media| rust_string(&media.media_type))
        .collect::<Vec<_>>();
    format!("&[{}]", values.join(", "))
}
