use super::rust::rust_crate;
use super::*;

pub(super) fn render_ts_package(contract: &ServiceContractV3) -> String {
    format!(
        "{{\n  \"name\": \"@ojos-generated/{}-client\",\n  \"version\": {},\n  \"private\": true,\n  \"type\": \"module\",\n  \"exports\": \"./src/index.ts\",\n  \"scripts\": {{\"typecheck\": \"tsc --noEmit\"}},\n  \"devDependencies\": {{\"typescript\": \"5.9.2\"}}\n}}\n",
        npm_name(&contract.service_id),
        ts_string(&contract.service_version.to_string()),
    )
}

pub(super) fn render_ts_config() -> String {
    "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"NodeNext\",\n    \"moduleResolution\": \"NodeNext\",\n    \"rootDir\": \"src\",\n    \"lib\": [\"ES2022\", \"DOM\"],\n    \"strict\": true,\n    \"noEmit\": true\n  },\n  \"include\": [\"src/**/*.ts\"]\n}\n".to_string()
}

pub(super) fn render_ts_client(contract: &ServiceContractV3) -> String {
    let mut source = r#"// Code generated by ojos service. DO NOT EDIT.
export interface Operation {
  readonly id: string;
  readonly method: string;
  readonly path: string;
  readonly audience: string;
  readonly permission?: string;
  readonly headerParameters: readonly HeaderParameter[];
  readonly requestContentTypes: readonly string[];
  readonly requestBodyRequired: boolean;
}

export interface HeaderParameter { readonly name: string; readonly required: boolean; }

export interface ContextSnapshot { readonly generation: number; readonly baseUrl: string; readonly token?: string; }
export type ContextSnapshotProvider = () => ContextSnapshot | Promise<ContextSnapshot>;
export type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

export interface ClientOptions { readonly context: ContextSnapshotProvider; readonly fetch?: FetchLike; readonly timeoutMs?: number; }
export interface CallOptions {
  readonly path?: Readonly<Record<string, string>>;
  readonly query?: Readonly<Record<string, string | number | boolean | undefined>>;
  readonly body?: unknown;
  readonly rawBody?: BodyInit;
  readonly headers?: Readonly<Record<string, string>>;
  readonly contentType?: string;
  readonly signal?: AbortSignal;
  readonly timeoutMs?: number;
  readonly idempotencyKey?: string;
}

export type ClientErrorKind = 'configuration' | 'timeout' | 'transport' | 'unauthorized' | 'forbidden' | 'not_found' | 'conflict' | 'rate_limited' | 'server';
export class ClientError extends Error {
  constructor(readonly kind: ClientErrorKind, message: string, readonly status?: number, options?: ErrorOptions) { super(message, options); }
}

export const operations = {
"#.to_string();
    for operation in sorted_operations(contract) {
        source.push_str(&format!(
            "  {}: {{ id: {}, method: {}, path: {}, audience: {},{} headerParameters: {}, requestContentTypes: {}, requestBodyRequired: {} }} as const,\n",
            ts_string(&operation.operation_id),
            ts_string(&operation.operation_id),
            ts_string(&operation.method),
            ts_string(&operation.provider_path),
            ts_string(&operation.audience),
            operation
                .permission
                .as_deref()
                .map(|permission| format!(" permission: {},", ts_string(permission)))
                .unwrap_or_default(),
            ts_header_parameters(operation),
            ts_request_content_types(operation),
            operation
                .request_body
                .as_ref()
                .map(|body| body.required)
                .unwrap_or(false),
        ));
    }
    source.push_str(
        r#"} satisfies Readonly<Record<string, Operation>>;

function expandPath(template: string, parameters: Readonly<Record<string, string>>): string {
  return template.replace(/\{([^}]+)\}/g, (_match: string, key: string) => {
    const value = parameters[key]; if (value === undefined) throw new ClientError('configuration', `missing path parameter ${key}`); return encodeURIComponent(value);
  });
}

function errorKind(status: number): ClientErrorKind | undefined {
  if (status === 401) return 'unauthorized'; if (status === 403) return 'forbidden'; if (status === 404) return 'not_found';
  if (status === 409) return 'conflict'; if (status === 429) return 'rate_limited'; if (status >= 500) return 'server'; return undefined;
}

const forbiddenHeaders = new Set(['authorization', 'host', 'cookie', 'set-cookie', 'connection', 'keep-alive', 'te', 'trailer', 'transfer-encoding', 'upgrade', 'content-length', 'content-type', 'idempotency-key', 'forwarded', 'via', 'expect', 'x-api-key', 'api-key']);
const forbiddenHeaderPrefixes = ['proxy-', 'sec-', 'x-forwarded-', 'x-ojos-caller-', 'x-ojos-gateway-', 'x-ojos-internal-', 'x-ojos-workload-'];
function forbiddenHeader(name: string): boolean { const normalized = name.trim().toLowerCase(); return forbiddenHeaders.has(normalized) || forbiddenHeaderPrefixes.some((prefix) => normalized.startsWith(prefix)); }
function validHeaderName(name: string): boolean { return /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/.test(name); }
function validHeaderValue(value: string): boolean { return !/[\x00-\x08\x0A-\x1F\x7F]/.test(value); }
function selectContentType(operation: Operation, requested: string | undefined, hasBody: boolean): string | undefined {
  const normalized = requested?.trim();
  if (!hasBody) { if (normalized) throw new ClientError('configuration', 'content type cannot be set without a request body'); return undefined; }
  if (!normalized) return operation.requestContentTypes[0];
  const declared = operation.requestContentTypes.find((value) => value.toLowerCase() === normalized.toLowerCase());
  if (!declared) throw new ClientError('configuration', `content type ${normalized} is not declared for operation ${operation.id}`);
  return declared;
}
function jsonMediaType(contentType: string | undefined): boolean {
  const mediaType = contentType?.split(';', 1)[0]?.trim().toLowerCase();
  return mediaType === 'application/json' || mediaType?.endsWith('+json') === true;
}

export class Client {
  readonly #context: ContextSnapshotProvider; readonly #fetch: FetchLike; readonly #timeoutMs: number;
  constructor(options: ClientOptions) { this.#context = options.context; this.#fetch = options.fetch ?? globalThis.fetch.bind(globalThis); this.#timeoutMs = options.timeoutMs ?? 30_000; }

  async call(operation: Operation, options: CallOptions = {}): Promise<Response> {
    const snapshot = await this.#context();
    if (!snapshot.baseUrl.trim()) throw new ClientError('configuration', 'context snapshot base URL is required');
    const target = new URL(snapshot.baseUrl.replace(/\/$/, '') + expandPath(operation.path, options.path ?? {}));
    for (const [key, value] of Object.entries(options.query ?? {})) if (value !== undefined) target.searchParams.set(key, String(value));
    if (options.body !== undefined && options.rawBody !== undefined) throw new ClientError('configuration', 'body and raw body cannot both be set');
    const hasBody = options.body !== undefined || options.rawBody !== undefined;
    if (operation.requestBodyRequired && !hasBody) throw new ClientError('configuration', 'request body is required');
    const contentType = selectContentType(operation, options.contentType, hasBody);
    const headers = new Headers();
    for (const [name, value] of Object.entries(options.headers ?? {})) {
      if (!validHeaderName(name)) throw new ClientError('configuration', `invalid header name ${JSON.stringify(name)}`);
      if (forbiddenHeader(name)) throw new ClientError('configuration', `header ${name} cannot be overridden`);
      if (!validHeaderValue(value)) throw new ClientError('configuration', `invalid value for header ${name}`);
      headers.append(name, value);
    }
    if (contentType) headers.set('Content-Type', contentType); if (snapshot.token) headers.set('Authorization', `Bearer ${snapshot.token}`);
    if (options.idempotencyKey?.trim()) headers.set('Idempotency-Key', options.idempotencyKey);
    for (const parameter of operation.headerParameters) if (parameter.required && !headers.get(parameter.name)?.trim()) throw new ClientError('configuration', `required header ${parameter.name} is missing`);
    const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(new DOMException('request timed out', 'TimeoutError')), options.timeoutMs ?? this.#timeoutMs);
    const abort = () => controller.abort(options.signal?.reason); options.signal?.addEventListener('abort', abort, { once: true });
    try {
      const requestBody = options.rawBody !== undefined ? options.rawBody : options.body === undefined ? undefined : jsonMediaType(contentType) ? JSON.stringify(options.body) : options.body as BodyInit;
      const response = await this.#fetch(target, { method: operation.method, headers, body: requestBody, signal: controller.signal });
      const kind = errorKind(response.status); if (kind) throw new ClientError(kind, `HTTP ${response.status}`, response.status); return response;
    } catch (error) {
      if (error instanceof ClientError) throw error;
      if (controller.signal.aborted && !options.signal?.aborted) throw new ClientError('timeout', 'request timed out', undefined, { cause: error });
      throw new ClientError('transport', 'request failed', undefined, { cause: error });
    } finally { clearTimeout(timeout); options.signal?.removeEventListener('abort', abort); }
  }
"#,
    );
    for operation in sorted_operations(contract) {
        source.push_str(&format!(
            "\n  {}(options: CallOptions = {{}}): Promise<Response> {{\n    return this.call(operations[{}], options);\n  }}\n",
            ts_identifier(&operation.operation_id),
            ts_string(&operation.operation_id),
        ));
    }
    source.push_str("}\n");
    source
}

pub(super) fn render_ts_events(contract: &ServiceContractV3) -> Result<String> {
    let mut source = r#"// Code generated by ojos service. DO NOT EDIT.
export interface EventDescriptor<T> { readonly type: string; readonly version: number; readonly schemaDigest: string; readonly delivery: string; readonly __payload?: T; }
export interface TypedEvent<T> { readonly descriptor: EventDescriptor<T>; readonly payload: T; }

type JsonSchema = Readonly<Record<string, unknown>>;

function assertObject(value: unknown, path: string): asserts value is Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error(`${path} must be an object`);
}

function assertExactKeys(value: Record<string, unknown>, allowed: readonly string[], path: string): void {
  const accepted = new Set(allowed);
  for (const key of Object.keys(value)) if (!accepted.has(key)) throw new Error(`${path} contains unknown field ${JSON.stringify(key)}`);
}

function validateEventValue(value: unknown, schema: JsonSchema, path: string): void {
  if ('const' in schema) {
    if (value !== schema.const) throw new Error(`${path} has an invalid constant value`);
    return;
  }
  if (Array.isArray(schema.enum)) {
    if (!schema.enum.includes(value)) throw new Error(`${path} is not an allowed value`);
    return;
  }
  switch (schema.type) {
    case 'object': {
      assertObject(value, path);
      const properties = schema.properties; assertObject(properties, `${path} schema properties`);
      assertExactKeys(value, Object.keys(properties), path);
      const required = schema.required;
      if (required !== undefined) {
        if (!Array.isArray(required) || !required.every((item): item is string => typeof item === 'string')) throw new Error(`${path} has an invalid required schema`);
        for (const key of required) if (!Object.prototype.hasOwnProperty.call(value, key)) throw new Error(`${path} is missing required field ${JSON.stringify(key)}`);
      }
      for (const [key, child] of Object.entries(properties)) {
        if (!Object.prototype.hasOwnProperty.call(value, key)) continue;
        assertObject(child, `${path}.${key} schema`);
        validateEventValue(value[key], child, `${path}.${key}`);
      }
      return;
    }
    case 'array': {
      if (!Array.isArray(value)) throw new Error(`${path} must be an array`);
      const items = schema.items; assertObject(items, `${path} items schema`);
      value.forEach((item, index) => validateEventValue(item, items, `${path}[${index}]`));
      return;
    }
    case 'string': if (typeof value !== 'string') throw new Error(`${path} must be a string`); return;
    case 'integer': if (typeof value !== 'number' || !Number.isSafeInteger(value)) throw new Error(`${path} must be a safe integer`); return;
    case 'number': if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${path} must be a finite number`); return;
    case 'boolean': if (typeof value !== 'boolean') throw new Error(`${path} must be a boolean`); return;
    default: throw new Error(`${path} has an unsupported schema type`);
  }
}

function assertWireEnvelope(value: unknown): asserts value is { readonly descriptor: Record<string, unknown>; readonly payload: unknown } {
  assertObject(value, 'event'); assertExactKeys(value, ['descriptor', 'payload'], 'event');
  if (!Object.prototype.hasOwnProperty.call(value, 'payload')) throw new Error('event is missing payload');
  assertObject(value.descriptor, 'event.descriptor');
  assertExactKeys(value.descriptor, ['type', 'version', 'schemaDigest', 'delivery'], 'event.descriptor');
}

"#.to_string();
    for event in all_events(contract) {
        let name = ts_type(&format!("{}V{}", event.event_type, event.version));
        source.push_str(&render_ts_payload(&name, &event.payload_schema)?);
        let schema = serde_json_canonicalizer::to_vec(&event.payload_schema)
            .map_err(CodegenError::Serialize)?;
        let schema =
            String::from_utf8(schema).map_err(|error| CodegenError::Drift(error.to_string()))?;
        source.push_str(&format!(
            "const {}PayloadSchema = {schema} as const satisfies JsonSchema;\nexport const {name}Descriptor = {{ type: {}, version: {}, schemaDigest: {}, delivery: {} }} as const satisfies EventDescriptor<{name}Payload>;\nexport type {name} = TypedEvent<{name}Payload>;\n\nfunction assert{name}Payload(value: unknown): asserts value is {name}Payload {{ validateEventValue(value, {}PayloadSchema, 'payload'); }}\nfunction assert{name}(value: unknown): asserts value is {name} {{\n  assertWireEnvelope(value);\n  if (value.descriptor.type !== {name}Descriptor.type || value.descriptor.version !== {name}Descriptor.version || value.descriptor.schemaDigest !== {name}Descriptor.schemaDigest || value.descriptor.delivery !== {name}Descriptor.delivery) throw new Error('event descriptor mismatch');\n  assert{name}Payload(value.payload);\n}}\nexport function new{name}(payload: {name}Payload): {name} {{ assert{name}Payload(payload); return {{ descriptor: {name}Descriptor, payload }}; }}\nexport function encode{name}(value: {name}): string {{ assert{name}(value); return JSON.stringify(value); }}\nexport function decode{name}(json: string): {name} {{\n  const value: unknown = JSON.parse(json); assert{name}(value); return value;\n}}\n\n",
            ts_identifier(&name),
            ts_string(&event.event_type),
            event.version,
            ts_string(&event.schema.digest),
            ts_string(&event.delivery),
            ts_identifier(&name),
        ));
    }
    while source.ends_with("\n\n") {
        source.pop();
    }
    Ok(source)
}

pub(super) fn render_ts_payload(event_name: &str, schema: &Value) -> Result<String> {
    let mut declarations = String::new();
    let mut names = BTreeSet::new();
    render_ts_object(
        &format!("{event_name}Payload"),
        schema,
        &mut declarations,
        &mut names,
    )?;
    Ok(declarations)
}

pub(super) fn render_ts_object(
    name: &str,
    schema: &Value,
    output: &mut String,
    names: &mut BTreeSet<String>,
) -> Result<()> {
    insert_identifier(names, name.to_string(), "TypeScript event payload")?;
    let (properties, required) = schema_properties(schema)?;
    let mut nested = String::new();
    output.push_str(&format!("export interface {name} {{\n"));
    for (property, property_schema) in properties {
        let nested_name = format!("{name}{}", ts_type(property));
        let field_type = ts_schema_type(&nested_name, property_schema, &mut nested, names)?;
        output.push_str(&format!(
            "  readonly {}{}: {field_type};\n",
            ts_string(property),
            if required.contains(property.as_str()) {
                ""
            } else {
                "?"
            }
        ));
    }
    output.push_str("}\n\n");
    output.push_str(&nested);
    Ok(())
}

pub(super) fn ts_schema_type(
    name: &str,
    schema: &Value,
    nested: &mut String,
    names: &mut BTreeSet<String>,
) -> Result<String> {
    Ok(match schema_kind(schema)? {
        "object" => {
            render_ts_object(name, schema, nested, names)?;
            name.to_string()
        }
        "array" => {
            let items = schema_object(schema)?
                .get("items")
                .ok_or_else(|| CodegenError::Drift("event array needs items".to_string()))?;
            format!(
                "readonly {}[]",
                ts_schema_type(&format!("{name}Item"), items, nested, names)?
            )
        }
        "string"
            if schema_object(schema)?.contains_key("enum")
                || schema_object(schema)?.contains_key("const") =>
        {
            schema_string_values(schema)?
                .into_iter()
                .map(ts_string)
                .collect::<Vec<_>>()
                .join(" | ")
        }
        "string" => "string".to_string(),
        "integer" | "number" => "number".to_string(),
        "boolean" => "boolean".to_string(),
        kind => {
            return Err(CodegenError::Drift(format!(
                "unsupported event type {kind}"
            )));
        }
    })
}

pub(super) fn npm_name(value: &str) -> String {
    rust_crate(value)
}

pub(super) fn ts_identifier(value: &str) -> String {
    let mut words = words(value).into_iter();
    let mut output = words
        .next()
        .unwrap_or_else(|| "operation".to_string())
        .to_ascii_lowercase();
    for word in words {
        output.push_str(&go_exported(&word));
    }
    if output.starts_with(|character: char| character.is_ascii_digit())
        || matches!(
            output.as_str(),
            "break" | "case" | "class" | "delete" | "function" | "new" | "return" | "throw"
        )
    {
        output.insert_str(0, "operation");
    }
    output
}

pub(super) fn ts_type(value: &str) -> String {
    go_exported(value)
}

pub(super) fn ts_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

pub(super) fn ts_header_parameters(operation: &ApiOperationV3) -> String {
    let values = operation
        .parameters
        .iter()
        .filter(|parameter| parameter.location == "header")
        .map(|parameter| {
            format!(
                "{{ name: {}, required: {} }}",
                ts_string(&parameter.name),
                parameter.required
            )
        })
        .collect::<Vec<_>>();
    format!("[{}]", values.join(", "))
}

pub(super) fn ts_request_content_types(operation: &ApiOperationV3) -> String {
    let values = operation
        .request_body
        .iter()
        .flat_map(|body| &body.content)
        .map(|media| ts_string(&media.media_type))
        .collect::<Vec<_>>();
    format!("[{}]", values.join(", "))
}
