// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"ojos-user-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: healthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: readyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/users/me",
					Handler: requireOperationPermission(serverCtx, "user.profile.read.self", getMyProfileHandler(serverCtx)),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/users/me",
					Handler: requireOperationPermission(serverCtx, "user.profile.update.self", updateMeHandler(serverCtx)),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/users/me/preferences",
					Handler: requireOperationPermission(serverCtx, "user.profile.read.self", getMyPreferencesHandler(serverCtx)),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/api/users/me/preferences",
					Handler: requireOperationPermission(serverCtx, "user.profile.update.self", updateMyPreferencesHandler(serverCtx)),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:user_id/profile",
					Handler: requireOperationPermission(serverCtx, "user.profile.read.any", adminGetProfileHandler(serverCtx)),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/admin/users/:user_id/profile",
					Handler: requireOperationPermission(serverCtx, "user.profile.update.any", adminUpdateProfileHandler(serverCtx)),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:user_id/stats",
					Handler: requireOperationPermission(serverCtx, "user.stats.read", adminGetStatsHandler(serverCtx)),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/users/:user_id/preferences",
					Handler: requireOperationPermission(serverCtx, "user.profile.read.any", adminGetPreferencesHandler(serverCtx)),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/admin/users/:user_id/preferences",
					Handler: requireOperationPermission(serverCtx, "user.profile.update.any", adminUpdatePreferencesHandler(serverCtx)),
				},
			}...,
		),
	)

	if serverCtx.Managed {
		return
	}

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserContextMiddleware},
			[]rest.Route{
				{Method: http.MethodGet, Path: "/api/users/:user_id/preferences", Handler: getPreferencesHandler(serverCtx)},
				{Method: http.MethodPatch, Path: "/api/users/:user_id/preferences", Handler: updatePreferencesHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/api/users/:user_id/profile", Handler: getProfileHandler(serverCtx)},
				{Method: http.MethodPatch, Path: "/api/users/:user_id/profile", Handler: updateProfileHandler(serverCtx)},
				{Method: http.MethodGet, Path: "/api/users/:user_id/stats", Handler: getStatsHandler(serverCtx)},
			}...,
		),
	)
}
