[package]
name = "ojos-orchestrator-tui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
clap.workspace = true
crossterm.workspace = true
orchestrator-legacy.workspace = true
orchestrator-manager.workspace = true
ojos-orchestrator-installer.workspace = true
ratatui.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ureq = { version = "3.3", default-features = false, features = ["rustls"] }
