[package]
name = "orchestrator-core"
version.workspace = true
edition.workspace = true

[dependencies]
regex.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2 = "0.10"
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
